### ISSUE TITLE
switch to another javascript linter, jshint is non-free

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1020]
https://github.com/jshint/jshint/blob/master/src/jshint.js
> The Software shall be used for Good, not Evil.

https://wiki.debian.org/qa.debian.org/jsonevil

Might have to remove this in the meantime :-(

**Comment by mr-c** [comment]
Looks like `eslint` might be a good candidate: https://eslint.org/docs/developer-guide/nodejs-api#linter
`npm-bundle` produces a 3.4MB tarball; we need to find a way to get that down to a single javascript file...

**Comment by kinow** [comment]
I remember seeing jshint in some projects some time ago, but in the past few years I've only used `eslint`. Might be able to tackle this one when I find time (good to check what's the status of the latest `eslint`, I think I'm using older versions).

**Comment by mr-c** [comment]
Oh, this was fixed in https://github.com/common-workflow-language/cwltool/commit/f0a844af6f93883fcacb3572a6366124a50d0909 !
