### ISSUE TITLE
Docker image for cwltool does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by suecharo** [common-workflow-language/cwltool#1033]
## Expected Behavior
- Working https://hub.docker.com/r/commonworkflowlanguage/cwltool

## Actual Behavior
- Does not work...

```
$ docker pull commonworkflowlanguage/cwltool
Using default tag: latest
latest: Pulling from commonworkflowlanguage/cwltool
81033e7c1d6a: Pull complete 
9b61101706a6: Pull complete 
d0230414692f: Pull complete 
8017bde2e9e0: Pull complete 
69085333b636: Pull complete 
7bfb9b44446e: Pull complete 
6a50fee2bf7c: Pull complete 
c876db03cb9f: Pull complete 
50ff3a734fd6: Pull complete 
Digest: sha256:efab1df45d351a613951d50a90673954b007c705f4eeedbeeb4b780e39bd0660
Status: Downloaded newer image for commonworkflowlanguage/cwltool:latest

$ docker run --privileged -ti --volume=$PWD:/tmp/workdir -w=/tmp/workdir commonworkflowlanguage/cwltool $*
ERROR: cwltool cannot work inside a container without access to docker
Launch the container with the option -v /var/run/docker.sock:/var/run/docker.sock
```

---

This Issue is very similar to Issue #546.
I talked to him face-to-face, and created a really moving Dockerfile.

https://github.com/suecharo/cwltool_in_container

The above code seems to work only on Linux due to differences in file system and file path of socket. When running on Mac or Windows, it is necessary to modify the code.

## Workflow Code
Using https://github.com/hacchy1983/CWL-workflows

## Your Environment
Ubuntu: 16.04

```bash
$ docker --version
Docker version 18.09.0, build 4d60db4
$ docker-compose --version
docker-compose version 1.23.1, build b02f1306
```

**Comment by inutano** [comment]
How's it going with the Docker container of cwltool available on Docker hub, @mr-c @tetron ? Is anyone working on improving the container image there?

We're testing to use a docker-compose.yml to launch a cwltool container which mounts /var/run/docker.sock to run tool containers beside the cwltool container. We'd be happy to provide it as a way to run cwltool via Docker.

**Comment by mr-c** [comment]
I'm not personally working on it. PRs are welcome!

**Comment by suecharo** [comment]
The command described in the link below is running.

https://github.com/common-workflow-language/cwltool/blob/master/cwl-docker.sh

However, the command described in the link below is NOT running.

https://hub.docker.com/r/commonworkflowlanguage/cwltool
