### ISSUE TITLE
ERROR: genrsa: Can't open "/etc/apache2/ssl/pass.key" for writing, Read-only file system

### ISSUE THREAD

**Issue by Johnnywang92** [common-workflow-language/cwltool#1060]
when I run the cwl tools on MAC, I gat an error message as following. Any suggestion? 
```
genrsa: Can't open "/etc/apache2/ssl/pass.key" for writing, Read-only file system
[job bwa_index.cwl] Max memory used: 0MiB
[job bwa_index.cwl] Job error:
Error collecting output for parameter 'output':
bwa_index.cwl:30:5: Traceback (most recent call last):
bwa_index.cwl:30:5:
bwa_index.cwl:30:5:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 612, in collect_output_ports
bwa_index.cwl:30:5:     compute_checksum=compute_checksum)
bwa_index.cwl:30:5:
bwa_index.cwl:30:5:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 692, in collect_output
bwa_index.cwl:30:5:     raise
bwa_index.cwl:30:5:
bwa_index.cwl:30:5:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/schema_salad/sourceline.py", line 166, in __exit__
bwa_index.cwl:30:5:     raise self.makeError("\n".join(traceback.format_exception(exc_type, exc_value, tb)))
bwa_index.cwl:30:5:
WorkflowException: bwa_index.cwl:33:7: Traceback (most recent call last):
bwa_index.cwl:33:7:
bwa_index.cwl:33:7:   File "/Users/yifanwang/Test/CWL_work/venv_cwl/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 664, in collect_output
bwa_index.cwl:33:7:     if gb.startswith(outdir):
bwa_index.cwl:33:7:
bwa_index.cwl:33:7: AttributeError: 'CommentedMap' object has no attribute 'startswith'
[job bwa_index.cwl] completed permanentFail
[job bwa_index.cwl] {}
[job bwa_index.cwl] Removing input staging directory /var/folders/1m/zpv1ttyd3klg2ywkv8c_r4z40000gn/T/dVzS1t
[job bwa_index.cwl] Removing temporary directory /var/folders/1m/zpv1ttyd3klg2ywkv8c_r4z40000gn/T/BcLAm1
{}
Final process status is permanentFail
```

**Comment by mr-c** [comment]
Hello @Johnnywang92 

This issue is due to the fact that we don't run docker as the root user and by default the entire filesystem except the working directory is read-only.

You don't appear to be using the `BWA_FILES` feature of the `allenday/bwa-http-docker` container, so I suggest using a Docker container that meets [best practices](https://doi.org/10.12688/f1000research.15140.1) like [`quay.io/biocontainers/bwa:0.7.15--1`](https://quay.io/repository/biocontainers/bwa)

**Comment by ttubb** [comment]
Looks like i'm late to the party. I got the tool running by using another container aus mr-c suggested. One hint: You have to change
```
    outputBinding:
      glob: $(inputs.reference)
```
to
```
    outputBinding:
      glob: $(inputs.reference.basename)
```
to make the output collection work.

**Comment by Johnnywang92** [comment]
> Hello @Johnnywang92
> 
> This issue is due to the fact that we don't run docker as the root user and by default the entire filesystem except the working directory is read-only.
> 
> You don't appear to be using the `BWA_FILES` feature of the `allenday/bwa-http-docker` container, so I suggest using a Docker container that meets [best practices](https://doi.org/10.12688/f1000research.15140.1) like [`quay.io/biocontainers/bwa:0.7.15--1`](https://quay.io/repository/biocontainers/bwa)

Thanks

**Comment by Johnnywang92** [comment]
@mr-c @ttubb Thank you!  I changed the outputBinding and docker container, it worked. I am going read the user guide again and carefully.
