### ISSUE TITLE
RFC handling of umask for temporary directories

### ISSUE THREAD

**Issue by tiborsimko** [common-workflow-language/cwltool#1081]
## Expected Behavior

Temporary directories created by `cwltool` should respect the `umask` settings of the parent environment. For example, when I set `umask 002` before running `cwltool`, I would expect `cwltool` to create any files or directories according to this umask. 

## Actual Behavior

The `cwltool` seems to impose fixed 755 permissions in several places:

```console
$ git grep -Hni 0o0
cwltool/docker.py:262:                os.makedirs(host_outdir_tgt, 0o0755)
cwltool/job.py:536:            os.makedirs(dirname, 0o0755)
cwltool/process.py:228:            os.makedirs(os.path.dirname(entry.target), 0o0755)
cwltool/process.py:245:            os.makedirs(entry.target, 0o0755)
cwltool/process.py:251:                os.makedirs(entry.target, 0o0755)
cwltool/singularity.py:229:            os.makedirs(new_dir, 0o0755)
```

## Motivation

When running CWL workflows on the containerised [REANA](http://www.reana.io/) reproducible analysis platform, there are situations where the user wants to be able to run the Docker image under some particular non-root user identity (say UID=501). In order to guarantee being able to write to the mounted workspace in the job container, the user (1) belongs to a particular group (say GID=0 following [OpenShift guidelines](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines)) and (2) permissions on the workspace are set  via `umask 002` to be of the `drwxrwxr-x` nature. This is usually enough to address the need.  However, we have encountered an issue that `cwltool` seems to create some directories with fixed 755 permissions (see above), which fails. It would be good `cwltool` respects the parent umask setting or if this behaviour were configurable.

## RFC

Is there a particular reason for imposing fixed 755 in `cwltool`? Could we simply drop it and rely on the umask set by the parent environment? Alternatively, could we make it configurable?

**Comment by tetron** [comment]
I don't see anything wrong with that.  Please provide a PR that changes them to 0o0777 with appropriate tests.

**Comment by tiborsimko** [comment]
Closing as the PR was merged.
