### ISSUE TITLE
Remove --dry-run

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwltool#11]
It isn't tested and doesn't work.

**Comment by tetron** [comment]
@mr-c said ":-( I think `--dry-run` is important" so let's consider.  The option is poor define it's not totally clear what it should do for workflows.

**Comment by mr-c** [comment]
Maybe it should incorporate the functionality of cwl2script? (and be
renamed?)

**Comment by manu-chroma** [comment]
I don't see any arg with ``--dry-run`` in [main.py](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/main.py)
Am I looking at the wrong place?

**Comment by mr-c** [comment]
Thanks for checking this @manu-chroma  it was removed in https://github.com/common-workflow-language/cwltool/pull/234/files#diff-7e9ba38c5e8dd21caad9558b5d833a79L116
`git log -S dry-run --source --all`

**Comment by manu-chroma** [comment]
@mr-c thanks for including that command :)

**Comment by mr-c** [comment]
@manu-chroma The real command was https://www.google.lt/search?q=git+search+history+for+string :-)

**Comment by mr-c** [comment]
Which took me to https://stackoverflow.com/a/5816177/1585509

**Comment by manu-chroma** [comment]
> The real command was https://www.google.lt/search?q=git+search+history+for+string :-)

Haha :smile:

**Comment by fgvieira** [comment]
Dear all,

has this issue been solved? I am not sure what was the initial idea behind `--dry-run`, but I think it would be nice to have an option that would just print the actual commands without running them. Is this possible?

I searched a bit, but only found other users with the same issue, e.g. https://www.biostars.org/p/268851/

thanks,

**Comment by mr-c** [comment]
@fgvieira Can you share your use case for `--dry-run` in a new issue? It would be possible to bring back something similar to `--dry-run` for a single `CommandLineTool`, but for a `Workflow` it isn't really possible unless someone made a CWL-to-shell converter.
