### ISSUE TITLE
Reported memory usage for Docker runs

### ISSUE THREAD

**Issue by hh-astron** [common-workflow-language/cwltool#1109]
## Expected Behavior
cwltool reporting correct memory usage for Docker runs.

## Actual Behavior
memory usage calculation is not (always) correct

## Your Environment
* cwltool version: 
cwltool used by MC during tutorial session at ASTRON 30/4/2019

**Comment by tonyyzy** [comment]
Same behaviour was observed.
```
INFO [job CollectWgsMetrics.cwl] Max memory used: 1036124MiB
```

I would be really happy if my laptop actually has that much memory :p

**Comment by mr-c** [comment]
My advice: run a tool using docker stats output manually while also monitoring the memory usage, then dig into https://github.com/common-workflow-language/cwltool/blob/8d8512061f2367c90aac67bcbf92af1061b4af59/cwltool/job.py#L722 to find the logic bug
