### ISSUE TITLE
Replace galaxy-lib requirement with galaxy-tool-util

### ISSUE THREAD

**Issue by nsoranzo** [common-workflow-language/cwltool#1155]
I'm working on Planemo to replace its dependency on galaxy-lib (which will be basically deprecated with Galaxy release 19.09) with [galaxy-tool-util](https://pypi.org/project/galaxy-tool-util/). Unfortunately CWL support in Planemo via cwltool would break unless also cwltool moves to galaxy-tool-util.

I can do the necessary changes in cwltool when I'm back from holidays, in the mean time I wanted to check that's fine with you all.

**Comment by mr-c** [comment]
Fine by me!
