### ISSUE TITLE
should use os.path.join for --tmp-outdir-prefix

### ISSUE THREAD

**Issue by ionox0** [common-workflow-language/cwltool#1162]
## Expected Behavior
if `--tmp-outdir-prefix` is supplied as `/some/dir`, temporary directories will show up in `/some/dir` and be named as `XXXX`

## Actual Behavior
if `--tmp-outdir-prefix` is supplied as `/some/dir`, temporary directories will show up in `/some` and be named as `/dirXXXX`

## Workflow Code
```
cwltool --debug --preserve-entire-environment --tmpdir-prefix `pwd` --tmp-outdir-prefix `pwd` workflow.cwl inputs.yaml
```

## Full Traceback
No traceback, just location of tmp dirs

## Your Environment
* cwltool version: 
`cwltool 1.0.20181118133959`

<img width="543" alt="Screen Shot 2019-08-02 at 11 07 16 AM" src="https://user-images.githubusercontent.com/6385646/62379840-beb53c80-b515-11e9-857a-fef83df2207a.png">

My thinking is that there could be somewhere where folder and tmp dir are being combined as strings, without using the `os.path.join()` method.

It's also possible that this same behavior occurs with the `--tmpdir-prefix` as well.

Thank you!

**Comment by ionox0** [comment]
I just realized that perhaps this is intended, and the parameter is meant to be the prefix of the directory itself...

**Comment by tetron** [comment]
You should be able to supply `--tmp-outdir-prefix=/some/dir/` to have it do what you want.

**Comment by ionox0** [comment]
got it, thanks for the information!
