### ISSUE TITLE
Clarify if --preserve-environment works with docker/Singularity

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1163]
Inspired by https://github.com/common-workflow-language/common-workflow-language/pull/125#discussion_r125999920

And if not, do we want it to?

**Comment by rupertnash** [comment]
Having looked at the code while considering the next step of #1377, I don't think it does.

I have no strong opinion as to whether preserved variables should be passed to containers, but if they're not, then the user should be warned at the least. One problem is that the preserve options are given to an invocation of the tool which may ultimately run many tools with their own requirements on what environment they need.

Note that for singularity, the default behaviour is the opposite: by default all env vars are available inside the container and you must add `--cleanenv`.

**Comment by mr-c** [comment]
For singularity, it is executed inside a subprocess where we set the env vars (including the result of `--preserve-environment`) so then singularity would inherit them as we don't currently pass in `--clearenv` https://github.com/common-workflow-language/cwltool/blob/1fd8d9c585bfbd0f25ffb54a2d4d92570461da45/cwltool/singularity.py#L381

**Comment by rupertnash** [comment]
I don't think this is quite correct. The preserve options are only applied in `CommandLineJob.run` which is overriden by `ContainerCommandLineJob.run` (and it disnae call it's super). `ContainerCommandLineJob.run` passes `os.environ` to `create_runtime`

**Comment by mr-c** [comment]
> I don't think this is quite correct. The preserve options are only applied in `CommandLineJob.run` which is overriden by `ContainerCommandLineJob.run` (and it disnae call it's super). `ContainerCommandLineJob.run` passes `os.environ` to `create_runtime`

Good catch! So they aren't applied for singularity, lets not change anything for now, but do issue a warning.

**Comment by rupertnash** [comment]
What is the preferred behaviour here? I think I'm nearly done on #1378 apart from containers.

**Comment by mr-c** [comment]
Consistency between usage of the docker or singularity engines would be good.

So lets enable it for Docker as well and print a warning that it is kinda a bad idea in both cases

**Comment by mr-c** [comment]
We should also add a test to confirm that without this option, environment variable are NOT passed to the singularity container

**Comment by mr-c** [comment]
Sure!
