### ISSUE TITLE
conda package is way too old -- 2018-02-25 !!

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1180]
- [x] Remove from README?
- [ ] update the package?

**Comment by mr-c** [comment]
related https://github.com/conda-forge/cwltool-feedstock ?

**Comment by pvanheus** [comment]
The bioconda recipe has been deprecated, so the correct source is, as you noted @mr-c, the conda-forge feedstock. There are 4 un-merged PRs over there, generated by the auto-updating service from conda-forge. The error seems to be a missing dependency: `coloredlogs` (and perhaps `future` ?). Maintainers of that package are listed as @croth1 and @chapmanb, which might be out of date. Perhaps some additional maintainers can be sought?

**Comment by mr-c** [comment]
Thanks @pvanheus, I'm going to remove it from the readme for now.

**Comment by pvanheus** [comment]
I've opened a PR to address this https://github.com/conda-forge/cwltool-feedstock/pull/18 - so let's see if that gets merged soon.

**Comment by pvanheus** [comment]
@croth1 has updated the conda-forge recipe to the latest version (1.0.20190906054215) so this issue can be closed.

**Comment by tfmorris** [comment]
@mr-c Do you agree that this can be closed?
