### ISSUE TITLE
deprecate draft-2 & draft-3

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#119]

**Comment by manu-chroma** [comment]
This issue is probably related to excess content we have in ``cwltool/schemas/`` directory or is there more to this one?

**Comment by mr-c** [comment]
That and remove code branches that are specific to those draft versions, also rename `draft2tool.py`

**Comment by manu-chroma** [comment]
@mr-c any suggestions for renaming ``draft2tool.py``

**Comment by mr-c** [comment]
`tool.py` But include a `draft2tool.py` with a wildcard import of `tool.py` that also emits a warning

**Comment by manu-chroma** [comment]
Since ``schemas/`` is a git subtree, it doesn't make sense to remove ``draft-2`` and ``draft-3`` from that folder. Because they will be re-added in the next merge once again.  

Is that correct assumption?

**Comment by mr-c** [comment]
@manu-chroma That is a correct assumption, yes.

**Comment by manu-chroma** [comment]
@mr-c In that case #520 looks ready to merge. Pls review.

**Comment by mr-c** [comment]
@manu-chroma I've already nominated Peter Amstutz to review that PR :-)

**Comment by manu-chroma** [comment]
> That is a correct assumption, yes.

Any ideas for fixes?  Related: https://github.com/common-workflow-language/common-workflow-language/issues/413

**Comment by mr-c** [comment]
@manu-chroma I'd leave the schemas directory alone, we will address that as part of the repository reorganization

**Comment by anton-khodak** [comment]
Closed in #520
