### ISSUE TITLE
pass option "--entrypoint" to docker run

### ISSUE THREAD

**Issue by hubentu** [common-workflow-language/cwltool#1223]
Hi,

Is there a way to pass "--entrypoint /bin/bash" to docker run by cwltool?

I want to use another tool from a docker image that has entrypoint option. An option "--entrypoint /bin/bash" to `docker run` would work. But I couldn't find a way to pass docker run options from cwltool.

Thanks!

**Comment by mr-c** [comment]
Hello @hubentu , there is not such an option, sorry. The use of entrypoint is not recommended for scientific software containers: https://doi.org/10.12688/f1000research.15140.2
