### ISSUE TITLE
loosen ruaml.yaml version requirement?

### ISSUE THREAD

**Issue by Zymergen-phaverty** [common-workflow-language/cwltool#1235]
Good morning. I am interested in the very specific version requirement for ruaml.yaml. This causes me a bit of dependency conflict. Can I help update something in cwltool that would allow for a version of ruaml.yaml > 0.16.0 to be used?

**Comment by tetron** [comment]
The author of ruamel.yaml has repeatedly released point releases that have broken our code, so we have had to set conservative version constraints on the highest version that has been tested.  It may be that 0.16 works fine, it just hasn't been tested.

To update it, there's two things you need to do.  First, cwltool depends on schema_salad, so it needs a pull request to update its version pin on ruamel.yaml.   The pull request will run the schema_salad tests.  If all the tests pass with ruamel.yaml 0.16.x then we can merge it and make a new schema salad release.

https://github.com/common-workflow-language/schema_salad

Then you can update the version pin on cwltool.  The pull request will run the cwltool tests.  If all the tests pass with ruamel.yaml 0.16.x then we can merge it and make a new cwltool release.

**Comment by Zymergen-phaverty** [comment]
Great, I'll have a go at it. Thanks!

**Comment by Zymergen-phaverty** [comment]
I submitted a PR over at schema-salad. It looks like everything passes with ruaml.yaml 0.16.5 (the newest). I requested you as a reviewer.
https://github.com/common-workflow-language/schema_salad/pull/313
