### ISSUE TITLE
About usage of Factory class

### ISSUE THREAD

**Issue by giannisdoukas** [common-workflow-language/cwltool#1266]
Hello everyone. I am using cwltool python library to execute cwl. In the test suit, I have seen that you have a factory class for creating the executor for the workflow but in cwltool code, you do not use it. Actually the main function seems to be a lot more complicated rather than factory's code. So my question is if in order to use the cwltool as a library the suggested way is to follow your main's function logic or to initialize the tool with the factory method. 

Thank you for your time.

**Comment by tetron** [comment]
Hi @giannisdoukas it depends on what you want to do.

If you just want to load a CWL file and execute it, you can use the factory class.

If you want all the command line parsing and various additional features that are implemented in cwltool's main(), you should use that.

**Comment by giannisdoukas** [comment]
ok! thank you very much!
