### ISSUE TITLE
Supporting docker post-command arguments

### ISSUE THREAD

**Issue by fmigneault** [common-workflow-language/cwltool#1275]
Looking at the implementation, I feel like there are currently no way to provide additional arguments to docker. In some cases, this option would be useful such as for running commands with https://github.com/NVIDIA/nvidia-docker

I have found through the CLI argument ``--user-space-docker-cmd CMD`` that allows override of the 'docker' command (eg: udocker or else), but this override is placed **before** the enforced docker commands.

In the case of `nvidia-docker`, the docker command doesn't actually need to be modified (toolkit hook replaces it), but flag ``--gpus '[options]'`` must be given **after** ``docker run`` to allow integration of CUDA devices within the container.

I guess I could define a custom `RuntimeContext` to implement this behaviour, but I was wondering if it was something that could be considered for direct implementation in the CLI to avoid hacking the code? 

Would it be possible to add some kind of input argument like : 
``--user-space-docker-run-args "args0 args1"`` 

## Expected Behavior

Allow to make a call as follows (or similar) : 

```
cwltool --user-space-docker-run-args "--gpus all" [other-cwltool-args] process.cwl job.yml
```
Which would eventually run : 
```
docker run --gpus all --volumes [...] [other-docker-args] docker-image:tag 
```

**NOTE**:
This flag is allowed only with `run`, other will raise unknown argument.
The extra arguments must therefore be command based.

## Actual Behavior

Just doesn't work because GPU cannot be found.

## Your Environment
* cwltool version:  2.0.20200126090152

**Comment by mr-c** [comment]
Hello @fmigneault , thanks for your question.

As `cwltool` is the reference implementation of the CWL standards it should only implement behaviour defined there, otherwise workflow that were developed using it wouldn't be portable.

The discussion around specifying additional hardware requirements in CWL, like GPUs, is at https://github.com/common-workflow-language/common-workflow-language/issues/587

So I'm going to close this issue so that the conversation can continue over there.

FYI, `weaver` looks cool; would you want to present it to one of the weekly CWL video chats?

**Comment by fmigneault** [comment]
@mr-c Thanks for the info. And yes, I would be glad to present it.

**Comment by mr-c** [comment]
Great! I've scheduled you for the 2020-05-02 14:30 UTC meeting, if that works for you. You can sign up at https://groups.google.com/forum/#!forum/common-workflow-language to receive a calendar invitation or just connect to https://meet.jit.si/cwl at that time. Presentation slides are optional.

**Comment by fmigneault** [comment]
Sounds good!

**Comment by fmigneault** [comment]
> 
> 
> Great! I've scheduled you for the 2020-05-02 14:30 UTC meeting, if that works for you. You can sign up at https://groups.google.com/forum/#!forum/common-workflow-language to receive a calendar invitation or just connect to https://meet.jit.si/cwl at that time. Presentation slides are optional.

@mr-c 
I would like to validate the link/meetup, I'm connected but don't see any video updates or other joining.

**Comment by mr-c** [comment]
@fmigneault Pardon me, I got the date wrong!

At 2020-05-05 14:30 UTC (Tuesday) we will all connect at https://meet.jit.si/cwl 

I also gave the wrong link to sign up to receive calendar reminders for the meeting, it is https://groups.google.com/forum/#!forum/common-workflow-language-videochat-invites Note that the archive doesn't show the invitations, but they do get sent out

Sorry for the confusion!

**Comment by fmigneault** [comment]
@mr-c I see. I will probably need to leave around 15:00 UTC for other meetings but I can drop by for a quick 30min.

**Comment by mr-c** [comment]
Sure, we'll be schedule you for the beginning of the call. Sorry about the mix-up; we are looking forward to it!
