### ISSUE TITLE
Javascript with variable called "arguments" fails

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/cwltool#1284]
The following CWL fails on JS evaluation
```
class: CommandLineTool
cwlVersion: v1.0
requirements:
  InlineJavascriptRequirement: {}

baseCommand: [echo]
arguments:
  - position: 1
    valueFrom: |
      ${
        var arguments = 22;
        return arguments
      }
inputs: []
outputs: []
```

It can be made to run as expected by changing `arguments` to some other name.

**Comment by tetron** [comment]
"arguments" is a reserved word https://www.w3schools.com/js/js_reserved.asp

**Comment by kaushik-work** [comment]
Cool, thank you. I think that is a bug/feature on our side then. We'll likely raise warnings in our tooling. Any chance CWL 2.0 won't have JS and we replace everything with Python3 scripts? :)
