### ISSUE TITLE
CWL v1.0 as default when no version given?

### ISSUE THREAD

**Issue by brainstorm** [common-workflow-language/cwltool#140]
Perhaps this has been discussed earlier, sorry if so... but would it make sense to bump the "default version" to 1.0 when a tool does not have it specified instead of `draft-2`?

```
master01: 2016-07-29 15:03:39,597 WARNING: cwltool: No cwlVersion found, treating this file as draft-2.
```

**Comment by tetron** [comment]
I think it would be better to just error out if the version is missing.
