### ISSUE TITLE
Feature request: Add option to execute only a single workflow step

### ISSUE THREAD

**Issue by jdidion** [common-workflow-language/cwltool#1407]
I would like to execute just a single step of a workflow.

For example, call cwltool with `--target wf/step!` and have only that step executed, not the whole workflow starting from that step.

Update: I think it would be even better to generalize the interface, so that one could specify a range of steps to run. So, for example `--target wf/stepB-stepB` would run just step B and `--target wf/stepB-stepD` would run steps B, C, and D.

**Comment by jdidion** [comment]
So if I'm going by the output of --print-subgraph, then it looks like `--target B` already works as expected - it only runs step B. So it looks like it's just the documentation for the `--target` option is wrong in the README https://github.com/common-workflow-language/cwltool#running-only-part-of-a-workflow

**Comment by jdidion** [comment]
If you can confirm that `--target` works the way I expect then I will close this issue. Thanks!

**Comment by tetron** [comment]
What do you want to happen if there are downstream steps?  I the current behavior is "the target step and everything downstream from the target step".  So if there are no downstream steps, it will only run step B.

You can also set an output parameter as a target, and then it will only run the steps that contribute to the output parameter.  If there are no upstream steps from step B, it'll only run step B.

If you want to be able to arbitrarily clip some portion of the subgraph, that would be a great feature if you would like to work on it.

**Comment by jdidion** [comment]
I ran `cwltool --target B --print-subgraph my.cwl` on a workflow that has 4 steps. The output of --print-subgraph only shows step B.

**Comment by jdidion** [comment]
To be more specific, I ran `cwltool --target step2 --print-subgraph tests/subgraph/count-lines1-wf.cwl` and got 

```
{
    "class": "Workflow",
    "cwlVersion": "v1.0",
    "id": "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl",
    "inputs": [
        {
            "id": "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl#step1_output",
            "type": "File"
        }
    ],
    "outputs": [
        {
            "id": "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl#count_output",
            "outputSource": "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl#step2/output",
            "type": "int"
        }
    ],
    "steps": [
        {
            "id": "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl#step2",
            "in": [
                {
                    "id": "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl#step2/file1",
                    "source": "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl#step1_output"
                }
            ],
            "out": [
                "file:///Users/jdidion/projects/cwltool/tests/subgraph/count-lines1-wf.cwl#step2/output"
            ],
            "run": "file:///Users/jdidion/projects/cwltool/tests/subgraph/parseInt-tool.cwl"
        }
    ]
}
```

**Comment by tetron** [comment]
Are those steps connected A->B->C->D ?

The documented intention was that it would run B->C->D but it's been a long time since I worked on this feature.

The _intention_ was to mimic something like `make` where you could select a specific target to build out a file that combined several potentially independent workflows.

**Comment by tetron** [comment]
Ok, yea, when it says "it will run the workflow starting from that step." that means the downstream dependency graph not the linear list of steps in the file.  In that example, there are no downstream steps from step2.

**Comment by jdidion** [comment]
You're right - it's just that the second step was not connected to anything. When I try with a step that is connected downstream then all the steps are included.
