### ISSUE TITLE
Argcomplete not in requirements.txt

### ISSUE THREAD

**Issue by rupertnash** [common-workflow-language/cwltool#1408]
## Expected Behavior
All packages required by cwltool should be in requirements.txt with a suitable version specifier

## Actual Behavior
It's absent so the version of argcomplete is unknowable

## Your Environment
Current main ab713b6c3bd2c590deb725bd7ce0aab7b2764811

@lucasace - I see you added this, so perhaps you're in the best position to know the version requirement?

Thanks!

**Comment by lucasace** [comment]
I think it was `1.12.1` when i added it, there's just been one minor release after that, `>
=1.12.0` should be good enough

**Comment by rupertnash** [comment]
Thanks Lucas. I've made a PR adding this.

**Comment by mr-c** [comment]
Fixed in #1410 , thanks!
