### ISSUE TITLE
replace distutils.spawn usage

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1421]
Distutils is deprecated since 2014 and will be removed from the Python standard library in Python 3.12

https://www.python.org/dev/peps/pep-0632/

`distutils.spawn.find_executable` → `shutil.which`
`distutils.spawn.spawn` → `subprocess.run`

https://github.com/common-workflow-language/cwltool/search?q=distutils

**Comment by KushalBeniwal** [comment]
@mr-c I would like to work on this issue.
