### ISSUE TITLE
cwltool is not packing `Operation` definitions

### ISSUE THREAD

**Issue by jmfernandez** [common-workflow-language/cwltool#1466]
I have been trying [cwltool 3.1.20210616134059](https://github.com/common-workflow-language/cwltool/releases/tag/3.1.20210616134059) with a very naïve, single `Operation` step workflow. Both validation and graph generation work, but when I packed it

```bash
cwltool --pack abstract-cosifer-workflow_fail1.cwl > abstract-cosifer-workflow_fail1.packed.cwl
```
packed file fails on validation

```bash
cwltool --validate abstract-cosifer-workflow_fail1.packed.cwl
```
```
INFO /home/jmfernandez/projects/iPC/ipc_workflows/cosifer/cwl_abstract/.p/bin/cwltool 3.1.20210616134059
INFO Resolved 'abstract-cosifer-workflow_fail1.packed.cwl' to 'file:///home/jmfernandez/projects/iPC/ipc_workflows/cosifer/cwl_abstract/a/abstract-cosifer-workflow_fail1.packed.cwl'
ERROR Tool definition failed initialization:
Tool definition file:///home/jmfernandez/projects/iPC/ipc_workflows/cosifer/cwl_abstract/a/abstract-cosifer-workflow_fail1.packed.cwl#abstract-cosifer.cwl failed validation:
  Reference `#abstract-cosifer.cwl` not found in file `file:///home/jmfernandez/projects/iPC/ipc_workflows/cosifer/cwl_abstract/a/abstract-cosifer-workflow_fail1.packed.cwl`.
```

because the `Operation` defintion was not included. I evolved that workflow, in order to have two parallel steps: a `CommandLineTool` and an `Operation`. And I got the very same result: the Operation definition was not included.

Having a look at cwltool code, I have found that it is skipping Operation definitions:

https://github.com/common-workflow-language/cwltool/blob/8ec1eb78e4c70638737656ecbcce02a4f0041c49/cwltool/pack.py#L254-L255

In order to ease reproducibility of this issue, I'm providing you a zip file with the workflows [operation_not_included.zip](https://github.com/common-workflow-language/cwltool/files/6725435/operation_not_included.zip)

**Comment by mr-c** [comment]
Dear @jmfernandez ; thanks for your ideal issue report!

I don't think this was intentional. Can you send a PR to add `"Operation"` to this list, and a simplified test case? Thanks!

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwltool/pull/1467
