### ISSUE TITLE
CommentedMap object has no attribute startswith

### ISSUE THREAD

**Issue by Hexotical** [common-workflow-language/cwltool#1496]
Hi, I'm trying to run a workflow with salmon installed locally, and it's failing, i'm not sure if this is a bug or not? I'm new to using CWL and I've looked at the code and put a log statement. I don't feel it should be using an ordered dictionary?

---
## Expected Behavior
This should operate on a string as opposed to ordered dict

## Actual Behavior
Workflow breaks
## Workflow Code
```
cwlVersion: v1.2
class: CommandLineTool

baseCommand: salmon
arguments: [index]

inputs:
  index:
    type: Directory
    inputBinding:
      prefix: --index
  transcripts:
    type: File
    inputBinding:
      prefix: --transcripts

outputs:
  salmon_index:
    type: Directory
    outputBinding:
      glob: "$(inputs.index)"
```
## Full Traceback
```
CRITICAL ordereddict([('class', 'Directory'), ('location', 'file:///home/hexotical/bioinformatics-workflows/toil/cwl/salmon_index'), ('basename', 'salmon_index'), ('path', '/tmp/wy58t55z/stg81e82f93-f93c-43d3-9db2-9efbaf2be133/salmon_index'), ('dirname', '/tmp/wy58t55z/stg81e82f93-f93c-43d3-9db2-9efbaf2be133')])
ERROR [job salmonIndex] Job error:
("Error collecting output for parameter 'salmon_index':\nsalmonIndex.cwl:21:7: 'CommentedMap' object has no attribute 'startswith'", {}
```

## Your Environment
cwltool 3.0.20201203173111

**Comment by mr-c** [comment]
Thank you @Hexotical for your report and reproducible example! I've improved the error message in https://github.com/common-workflow-language/cwltool/pull/1497 ; can you check that out?

**Comment by Hexotical** [comment]
> Thank you @Hexotical for your report and reproducible example! I've improved the error message in #1497 ; can you check that out?

Yeah, the new error message clarifies it though i'm still not entirely sure how to fix the issue though that's more I feel cause im still learning how to use cwl.

**Comment by Hexotical** [comment]
Actually I got it to work, the error message clarified it nicely for me!
