### ISSUE TITLE
make_tool_notimpl used with newest release of cwltool

### ISSUE THREAD

**Issue by Panaetius** [common-workflow-language/cwltool#1525]
With the newest release of cwltool (3.1.20210921111717) we're seeing 
```
/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/cwltool/factory.py:70: in make
    load = load_tool.load_tool(cwl, self.loading_context)
/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/cwltool/load_tool.py:484: in load_tool
    return make_tool(uri, loadingContext)
/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/cwltool/load_tool.py:462: in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

toolpath_object = ordereddict([('class', 'Workflow'), ('id', 'file:///tmp/tmpn3gj89xx#b1bd0776-f513-4dce-8884-b4fb864103eb'), ('inputs',...s'), ('networkAccess', True)])]), ('cwlVersion', 'v1.2'), ('http://commonwl.org/cwltool#original_cwlVersion', 'v1.0')])
loadingContext = <cwltool.context.LoadingContext object at 0x7fba00df6cd0>

    def make_tool_notimpl(
        toolpath_object: CommentedMap, loadingContext: "LoadingContext"
    ) -> "Process":
>       raise NotImplementedError()
E       NotImplementedError
```
in our CI.

Did anything change that we're not aware of?

**Comment by mr-c** [comment]
Sorry about that @Panaetius ;  in #1526 I've reverted that change as it was just to quiet a Sphinx warning and thus not worth the problem it caused. I'll make a new release with that fix shortly.

I do recommend pinning your `cwltool` version as we don't have the resources currently to maintain a public stable API.

**Comment by Panaetius** [comment]
Thank you!

We usually pin to a minor version (to still get important bug/security fixes), but I'll change it so in the future we pin to specific versions for cwltool and check with the dependabot PRs before upgrading it.

**Comment by mr-c** [comment]
Fix released in https://pypi.org/project/cwltool/3.1.20210922130607/ a.k.a https://github.com/common-workflow-language/cwltool/releases/tag/3.1.20210922130607
