### ISSUE TITLE
Allow interpreted subclasses

### ISSUE THREAD

**Issue by fmigneault** [common-workflow-language/cwltool#1745]
I have recently attempted updating my code base (https://github.com/crim-ca/weaver), that uses `cwltool` to run CWL workflows with alternative tools, with latest versions (moving from old https://github.com/common-workflow-language/cwltool/tree/3.0.20200324120055 to recent https://github.com/common-workflow-language/cwltool/tree/3.1.20220913185150)

I encountered the following error during this process: 
```python
TypeError interpreted classes cannot inherit from compiled 
```
when calling this code in order to generate custom tool definitions:
https://github.com/crim-ca/weaver/blob/master/weaver/processes/wps_workflow.py#L81-L87

I have managed to work around this using:

```python
from typing import cast

cast(WpsWorkflow, WpsWorkflow(toolpath_object, loading_context, get_job_process_definition))
```

## Expected Behavior

I was wondering if the following definition applied to `cwltool.process.Process` would avoid this `cast` hack?

https://mypyc.readthedocs.io/en/latest/native_classes.html
```python
@mypyc_attr(allow_interpreted_subclasses=True)
```

## Actual Behavior
Allow directly inheriting from the Process class without typing cast workaround.

## Workflow Code
n/a

## Full Traceback
n/a

## Your Environment
* cwltool version: https://github.com/common-workflow-language/cwltool/tree/3.1.20220913185150

**Comment by mr-c** [comment]
Good catch; sorry I forgot about weaver when checking which classes are sub-classed;

Can you send a PR?

**Comment by mr-c** [comment]
@fmigneault Thanks! The fix is apart of the new `cwltool` release: https://github.com/common-workflow-language/cwltool/releases/tag/3.1.20221018083734 a.k.a. https://pypi.org/project/cwltool/3.1.20221018083734/
