### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by tfmorris** [common-workflow-language/cwltool#176]
It's great that the tool doesn't require Python 3 and still supports Python 2.7, but since it's a brand new development and Python 3 has been around for ages, it should support both.

In practice, this isn't that big a deal and just means doing things like using print functions (with `from __future__ import print_function`) instead of the 2.x style print keyword. Besides the print function, the other main incompatibility is division https://www.python.org/dev/peps/pep-0238/

**Comment by tetron** [comment]
Duplicate #8
