### ISSUE TITLE
Can not model/print RDF without running the workflow

### ISSUE THREAD

**Issue by j-steinbach** [common-workflow-language/cwltool#1774]
## Background

I am a researcher and want to analyze the interoperability of CWL workflows. For this I want to generate the RDF interpretation of as many workflows as I can get my hands on. _I am not interested in what the workflows actually do -- I just want the RDF interpretation(s)!_

## Expected Behavior

Running `cwltool --print-rdf custom-types.cw` should just print the RDF interpretation of the workflow.

## Actual Behavior

`Error: Tool  definition failed validation.` 

I am being required to provide the correct input files. Just adding empty files (`touch biom-convert-table.yaml`) fails as well.

## Workflow Code

The example from the docs: http://www.commonwl.org/user_guide/topics/custom-types.html#custom-types-cwl

## Full Traceback
```pytb
Paste the full traceback in case there is an exception
Run the workflow with ``--debug`` flag for more verbose logging 
```

## Your Environment
* cwltool version: 3.1.20221201130942

**Comment by mr-c** [comment]
Hello @j-steinbach and thanks for sharing your issue.

`cwltool --print-rdf` requires that the provided CWL file validate correctly. 

http://www.commonwl.org/user_guide/topics/custom-types.html#custom-types-cwl uses `$import: biom-convert-table.yaml` which means that `biom-convert-table.yaml` needs to be in the same folder as the main document.

When I create both files then `--print-rdf` works for me. I hope this solves your problem as well.

**Comment by j-steinbach** [comment]
Ty! It kinda makes sense that we need to validate first before generating the RDF. 

So I don't need the 'real' data to have the workflow run, but I should provide the workflow with everything it needs to validate? Ie. custom types. 

Providing a fake/empty `biom-convert-table.yaml` is a validation error, as the `biom-convert-table.yaml` is required for the workflow to correctly. It should be seen as supplement of the `.cwl` file.

To answer my question: A CWL workflow can be modeled to RDF without needing to be run. It does not need 'real' data to work. It just needs to validate.

---

I think this solves it. This issue can be closed. (I will close it myself in 24h, to give time for people to weigh in)
