### ISSUE TITLE
`--preserve-environment` doesn't seem to work

### ISSUE THREAD

**Issue by serverhorror** [common-workflow-language/cwltool#196]
Hi,

When Running cwl-runner (or cwltool) in combination with `--preserve-environment` the variables are _removed_ from the environment. I would expect them to be available.

It would also be nice to have an option like `--preserve-complete-environment` (I'm not sure this is opposing to the spec). We use a system called environment modules (bash functions to manipulate a smorgasboard of environment variables) and I currently don't see a way to use it with CWL other than manually specifying environment variables in the steps.

**cwl**

```
class: CommandLineTool
cwlVersion: v1.0
baseCommand: "env"

inputs: []
outputs: []
```

**Default run**

```
$ cwl-runner --debug env.cwl
/home/XXX/cwlSamples/bin/cwl-runner 1.0.20160919152321
Parsed job order from command line: {
    "id": "env.cwl",
    "job_order": null
}
[job env.cwl] initializing from file:///home/XXX/cwl-by-example/env.cwl
[job env.cwl] {
    "job_order": null
}
[job env.cwl] path mappings is {}
[job env.cwl] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "env"
    }
]
[job env.cwl] /tmp/tmpG1NXFi$ env
PATH=...[snipped]...
TMPDIR=/tmp/tmp4KcSP8
HOME=/tmp/tmpG1NXFi
[job env.cwl] completed success
[job env.cwl] {}
Final process status is success
[job env.cwl] Removing input staging directory /tmp/tmpczvlpk
[job env.cwl] Removing temporary directory /tmp/tmp4KcSP8
[job env.cwl] Removing empty output directory /tmp/tmpG1NXFi
{}
```

**Preserve some variables**

```
$ cwl-runner --debug --preserve-environment=PATH,LD_LIBRARY_PATH env.cwl
/home/marcherm/cwlSamples/bin/cwl-runner 1.0.20160919152321
Parsed job order from command line: {
    "id": "env.cwl",
    "job_order": null
}
[job env.cwl] initializing from file:///home/marcherm/cwl-by-example/env.cwl
[job env.cwl] {
    "job_order": null
}
[job env.cwl] path mappings is {}
[job env.cwl] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "env"
    }
]
[job env.cwl] /tmp/tmpHLE2yV$ env
HOME=/tmp/tmpHLE2yV
TMPDIR=/tmp/tmp3mrym2
[job env.cwl] completed success
[job env.cwl] {}
Final process status is success
[job env.cwl] Removing input staging directory /tmp/tmpuj_em7
[job env.cwl] Removing temporary directory /tmp/tmp3mrym2
[job env.cwl] Removing empty output directory /tmp/tmpHLE2yV
{}
```

**Comment by tetron** [comment]
That sounds like a bug.  Agree that there needs to be an option to inherit full environment.

**Comment by tetron** [comment]
Hi @serverhorror, yes it turns out there was a bug where using --preserve-environment with multiple environment variables didn't work.  

Pending fix in #199 enables you do use --preserve-environment multiple times and it will do the right thing.  It additionally adds an option --preserve-entire-environment.

**Comment by tetron** [comment]
Additionally, there are longer term plans to support environment modules via the http://www.commonwl.org/v1.0/CommandLineTool.html#SoftwareRequirement feature, but that is not currently implemented.

**Comment by tetron** [comment]
@serverhorror could you confirm this is fixed?

**Comment by Karhide** [comment]
Hi there,

Is --preserve_environment ENVVAR meant to work with Docker containers?

If I print os.environ from within a container launched as a result of a dockerRequirement then I find that my environment variable is not being preserved.

Bug or Working as intended?

Thanks!

**Comment by mr-c** [comment]
Hello @Karhide 

For (Docker) containers you should other methods:

1) either set the environment variable as part of the container creation (via Dockerfile or some other method)

- or -

2) Set the environment variable in the `CommandLineTool`, workflow step, or `Workflow` level using [EnvVarRequirement](http://www.commonwl.org/v1.0/CommandLineTool.html#EnvVarRequirement) in the `requirements` or `hints` section as appropriate: http://www.commonwl.org/user_guide/12-env/
