### ISSUE TITLE
cwltool hangs running fast jobs in Podman

### ISSUE THREAD

**Issue by kuanyili** [common-workflow-language/cwltool#1961]
#1883 and #1890 tried to address this issue, but it is still not solved.

## Cause Analysis

The behavior of how Podman handles cidfile changed since 4.4.0.

https://github.com/containers/podman/commit/3fee351c355788aed0d5f9e069f8b14ed7eb109a

Container ID file is now removed along with the container by Podman.

https://docs.podman.io/en/latest/markdown/podman-run.1.html#cidfile-file

So on a fast machine with Podman >= 4.4.0, there is a chance that we'll run into a race condition.

If we are relatively lucky, the job runs long enough, `cwltool` captures the cidfile, removes it, and Podman THROWS OUT A WARNING (cidfile not found).

And if we are unlucky, race condition occurs, `cwltool` HANGS INDEFINITELY in the loop

https://github.com/common-workflow-language/cwltool/blob/3.1.20231207110929/cwltool/job.py#L860

waiting for the cidfile which has already been created AND REMOVED by Podman.

Moving `time.sleep(1)` to the end of the loop might help a bit, but this is still no guarantee to avoid race condition. Currently I'm out of ideas for solving this issue in a correct way.

## Full Traceback

```pytb
Traceback (most recent call last):
  File "/home/user/miniforge3/envs/cwltool/bin/cwltool", line 11, in <module>
    sys.exit(run())
             ^^^^^
  File "cwltool/main.py", line 1457, in run
  File "cwltool/main.py", line 1301, in main
  File "cwltool/executors.py", line 62, in __call__
  File "cwltool/executors.py", line 145, in execute
  File "cwltool/executors.py", line 253, in run_jobs
  File "cwltool/job.py", line 843, in run
  File "cwltool/job.py", line 336, in _execute
  File "cwltool/job.py", line 986, in _job_popen
  File "cwltool/job.py", line 861, in docker_monitor
KeyboardInterrupt
```

## Your Environment

* cwltool version: 3.1.20231207110929

**Comment by mr-c** [comment]
Hello @kuanyili ; thank you for your persistence with podman!

Two things: 

1) I think the return statement at https://github.com/common-workflow-language/cwltool/blob/29af2be2861058fb721afe48a8da271b17a7846f/cwltool/job.py#L872 needs to de-indented one level.

2) the logic to set `cleanup_cidfile` at https://github.com/common-workflow-language/cwltool/blob/29af2be2861058fb721afe48a8da271b17a7846f/cwltool/job.py#L838 probably needs to take into account the podman version.

**Comment by kuanyili** [comment]
Hi @mr-c ! Thank you for the speedy reply!

Point 1 seems promising.

However, there is something I would like to discuss related to point 2.

I noticed that if we run a Docker/Podman job without `--cidfile-dir`, cwltool creates a temporary directory to store cidfile.
https://github.com/common-workflow-language/cwltool/blob/3.1.20231207110929/cwltool/docker.py#L394
And currently there is no mechanism in place to clean that up. `/tmp` will be filled up with these directories after several job runs.

My naive approach: As the cidfile cleanup is performed ONLY when `--cidfile-dir` is not specified,
https://github.com/common-workflow-language/cwltool/blob/3.1.20231207110929/cwltool/job.py#L838
instead of cleaning up the cidfile, let's remove the directory it is under altogether with `os.rmtree`!

But here is the catch: If we take Podman version into account, my naive approach obviously won't work. As we skip the cleanup with newer versions of Podman, that temporary directory stays.

What do you recommend? Should we just implement point 1 and leave point 2 for future discussion? If so, do you prefer that I submit a PR or do you think it would be easier for you to commit the change?
