### ISSUE TITLE
w3 YML does not exist.

### ISSUE THREAD

**Issue by muppetjones** [common-workflow-language/cwltool#225]
I am having many issues trying to use CWL and `schema_salad`, but the latest is due to a hard-coded filename not existing:

```shell
/usr/local/bin/cwltool 1.0.20161107145355
Tool definition failed initialization:
('https://w3id.org/cwl/CommonWorkflowLanguage.yml', HTTPError(u'404 Client Error: Not Found for url: https://w3id.org/cwl/CommonWorkflowLanguage.yml',))
```

**Comment by mr-c** [comment]
Hello @muppetjones , I am sorry to hear you are having issues; it is frustrating when things don't work at the very beginning!

Can you tell me more about how you installed `cwltool` and how you are invoking it? Looks like you did a system wide install -- we normally use virtualenvs. It would also be helpful to know your operating system and Python version.

```
python -V
pip show schema_salad
```

If you are calling cwltool with a specific input file(s) then it would be useful to see them. Are you able to run any of the examples from the user guide? http://www.commonwl.org/v1.0/UserGuide.html

**Comment by yuankunzhu** [comment]
@mr-c I got the same issue, failed for the "First example -- Hello world" program.
```
$ cwl-runner 1st-tool.cwl echo-job.yml
/usr/local/bin/cwl-runner 1.0.20160610111115
Tool definition failed initialization:
('https://w3id.org/cwl/CommonWorkflowLanguage.yml', HTTPError('404 Client Error: Not Found',))
```
also FYI
```
$ python -V
Python 2.7.6

$ pip show schema_salad
Name: schema-salad
Version: 1.12.20160610104117
Summary: Schema Annotations for Linked Avro Data (SALAD)
Home-page: https://github.com/common-workflow-language/common-workflow-language
Author: Common workflow language working group
Author-email: common-workflow-language@googlegroups.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: rdflib, requests, typing, rdflib-jsonld, mistune, avro, ruamel.yaml
```

**Comment by mr-c** [comment]
Hello @yuankunzhu, `cwltool` version 1.0.20160610111115 predates the release of CWL v1.0. Can you upgrade to a newer version?

**Comment by yuankunzhu** [comment]
@mr-c cwltool updated, still get the same issue:
```
$ cwl-runner 1st-tool.cwl echo-job.yml
/usr/local/bin/cwl-runner 1.0.20160531173804
Tool definition failed initialization:
('https://w3id.org/cwl/CommonWorkflowLanguage.yml', HTTPError('404 Client Error: Not Found',))
```

**Comment by mr-c** [comment]
@yuankunzhu Thank you for the update. Somehow your upgrade went back in time! 1.0.20160531173804 means May 31, 2016, your previous version was from June 10th, 2016.

Can you try a version from 2017? The latest version of `cwltool` is [1.0.20170224141733](https://pypi.python.org/pypi/cwltool/1.0.20170224141733), from February 24th, 2017.

**Comment by yuankunzhu** [comment]
Hi @mr-c, thanks for your reply. It works well now. 
What I did was `pip uninstall cwl-runner` & `pip uninstall cwlref-runner`, then `pip install cwlrel-runner` and `cwltool` came to `1.0.20160531173804`, then I did `pip install --upgrade cwltool` and it's finally upgraded.

**Comment by mr-c** [comment]
@yuankunzhu Hurray! You are very welcome

@muppetjones I don't think you had a similar problem, but since I haven't heard back from you in several months I'm going to close this issue for now. Please re-open this issue if you are still having troubles.
