### ISSUE TITLE
check for valid version of node / nodejs

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#254]
for example, v0.10.25 is too old 
https://www.biostars.org/p/226909/#226917

**Comment by manu-chroma** [comment]
if im not wrong, this would require making changes to ``cwltool/sandboxjs.py`` https://github.com/common-workflow-language/cwltool/blob/master/cwltool/sandboxjs.py#L33 

after sucessful node detection, we need to check the version and if it's below the threshold, raise a runtime exception and exit the program. probably output a logging message before doing that. 
 
@mr-c @tetron

**Comment by mr-c** [comment]
@manu-chroma A good plan, yep!

**Comment by manu-chroma** [comment]
any threshold version to check against?

currently setting it to ``v0.10.25``

**Comment by tetron** [comment]
The spec currently sets the minimum at ECMAScript 5.1, which seems to be well supported by Node.js 0.10.25.  This is the version that ships in Ubuntu 14.04.  Debian 8 ships with Node.js 0.10.29.

There's lots of goodies in ECMAScript 6+, but according to http://node.green/ you want to be using Node.js 6.4.0 or later to have good compliance with the standards.

We can consider bumping the requirement to ECMAScript 6 in the v1.1 spec.

**Comment by manu-chroma** [comment]
for the time being, what would you suggest should go in ``cwltool`` ?

should we stick to the current specification or set the minimum threshold version to Node.js 6.4.0 ?
i can open an issue in ``common-workflow-language/common-workflow-language`` for the same. 

relevant PR: https://github.com/common-workflow-language/cwltool/issues/337

**Comment by mr-c** [comment]
@manu-chroma The minimum version to detect should be `0.10.25` as we are not changing the CWL specifications at this time.

**Comment by manu-chroma** [comment]
sticking to ``0.10.25`` for the PR then 😄
