### ISSUE TITLE
Add ubuntu group to ubuntu user in cwl-runner's docker command

### ISSUE THREAD

**Issue by Jeltje** [common-workflow-language/cwltool#265]
# Feature request

Currently, when I run 
`cwl-runner tool.cwl tool.json`
The docker command contains this:
```
    --user=1000 \
```
This results in my files being owned by user ubuntu in group root:
`-rw-r--r-- 1 ubuntu root   824831998 Jan  4 20:16 dbSNP_chr17.vcf`

Using `--user=1000:1000` will create the correct group:
`-rw-r--r-- 1 ubuntu ubuntu 104046759 Jan  4 20:17 dbSNP_chr17.vcf.gz`

Can this be changed?

**Comment by manu-chroma** [comment]
A very straightforward fix will be to change this string: https://github.com/common-workflow-language/cwltool/blob/master/cwltool/job.py#L400

But I am not very sure how ``UID`` works.

**Comment by mr-c** [comment]
1. get the "egid" (effective group ID), just like in https://github.com/common-workflow-language/cwltool/blob/master/cwltool/job.py#L394
2. change https://github.com/common-workflow-language/cwltool/blob/master/cwltool/job.py#L400
to 
`runtime.append(u"--user=%s:%s" % (euid, egid))
