### ISSUE TITLE
nameroot field is not generated for File in input

### ISSUE THREAD

**Issue by psafont** [common-workflow-language/cwltool#268]
When defining input files only by path the nameroot field does not get generated by the cwl to be consumed by the steps when using the requirement `StepInputExpressionRequirement`.

I made a little repo where it can be easily reproduced: https://gitlab.com/unduthegun/cwl-test

OS: Linux
Python: 2.7.13
cwltool: 1.0.20170105144051

**Comment by kapilkd13** [comment]
Hi, To solve this bug, what I am doing is checking(in steps.input ) if `nameroot` exists, if it doesn't then generate `nameroot` using `basename` (if it exist). But I am not sure where to put this condition.
I am thinking of putting it in https://github.com/common-workflow-language/cwltool/blob/master/cwltool/workflow.py#L148 . Is this approach correct.

**Comment by kapilkd13** [comment]
I guess I was wrong. Better thing to do would be to do the changes in `job_order_object`  while it is being resolved, before it is passed to `workflow`. My changes are here https://github.com/common-workflow-language/cwltool/pull/338
