### ISSUE TITLE
Dockerized tools fail if they don't respect TMPDIR

### ISSUE THREAD

**Issue by dleehr** [common-workflow-language/cwltool#30]
As of e645adecab98417f96e7676ab54e0b60b042da61, cwltool sets `--read-only=true` when running docker. This makes the container's file system read-only, excepting only volumes attached as **rw** at runtime. I think this is a great idea, but have run into issues with `/tmp`.

Since `/tmp` is not a volume, it is read-only inside the container. I do see that the `TMPDIR` variable is set to a **rw** volume, but many tools don't respect `TMPDIR`, still try to write to `/tmp`, and now fail.

I can probably work around this in a few cases, but I figured it was worth discussing. Is there a reason the job's temp directory is mounted at `/tmp/job_tmp` instead of just `/tmp`?

**Comment by tetron** [comment]
The main reason is that q

**Comment by tetron** [comment]
Sorry hit submit too fast.

The reasoning is that when tools are not running in a container they should still be somewhat isolated. If the temporary directory is /tmp and it is shared among running tools then tools could interfere with each other's files or communicate by back channel in a nonportable way.

That said, for containers we could go ahead and specify that the temporary directory is always /tmp.  I agree it is important to favor the most compatible behavior.

**Comment by tetron** [comment]
@denis-yuen and I were just talking about this on gitter.  I think the solution is to be to add this to your Dockerfile:

```
VOLUME /tmp
```

The only hiccup is that cwltool also has mounts points in /tmp, which might interact badly (certainly it's a bit confusing).  I will update cwltool to use different mount points inside Docker.

**Comment by tetron** [comment]
I've gone ahead and made it so TMPDIR is /tmp and is a writable volume.  The CWL output directory is now /var/spool/cwl.  Please close the issue if your problem has been addressed.

**Comment by dleehr** [comment]
That works, thanks!
