### ISSUE TITLE
excess empty argument

### ISSUE THREAD

**Issue by annam30** [common-workflow-language/cwltool#300]
Hello!
Excess empty argument appends in command line bindings:
```
[job WgetUrl] path mappings is {}
[job WgetUrl] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "datum": ""
    }, 
```

Because of this appears an empty string after docker image:
```
[job WgetUrl] /tmp/tmpo0Ot3p$ docker \
    run \
    -i \
    --volume=/tmp/tmpo0Ot3p:/var/spool/cwl:rw \
    --volume=/tmp/tmp_DQZJN:/tmp:rw \
    --workdir=/var/spool/cwl \
    --read-only=true \
    --user=1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/var/spool/cwl \
    avkitex/wget:v1 \
    '' \
    https://en.wikipedia.org/wiki/Category:Bioinformatics_software
```

[testWgetCount.zip](https://github.com/common-workflow-language/cwltool/files/794361/testWgetCount.zip)

**Comment by mr-c** [comment]
Hello @annam30 

Thank you for sharing your issue.

The reference doesn't appear to be violating the spec, as your tools have an empty entry for `baseCommand`:
```
        "baseCommand": [
          ""
        ]
```

According to http://www.commonwl.org/v1.0/CommandLineTool.html#Input_binding the last step to creating the command line is "[to i]nsert elements from baseCommand at the beginning of the command line."

[Your Docker image](https://hub.docker.com/r/avkitex/wget/) has `ENTRYPOINT ["/usr/bin/wget"]`. In CWL we don't use Docker containers with entry points, as the CWL implementations create the command line from the tool definition.

I recommend removing the `ENTRYPOINT` from your Docker image and changing your CWL definition to have `baseCommand: wget` (or `"baseCommand": [ "wget" ]` to match your formatting)

**Comment by annam30** [comment]
Thank you very match for the answer!

**Comment by mr-c** [comment]
@annam30 You are very welcome! I am going to close this issue. Anytime you have a question please feel free to open another issue here, or post to http://www.BioStars.Org/t/cwl using the `cwl` tag
