### ISSUE TITLE
path to full python2+python3 support

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#310]
Building off of https://github.com/common-workflow-language/cwltool/pull/306, #287, and #305 

- [x] populate the `typeshed/3` directory with any needed type stubs
  - [x] submit these type stubs to https://github.com/python/typeshed
- [ ] add code to use `avro-python3` as needed here and in `schema_salad`
- [x] pass `mypy` without `--py2` (test with `make mypy3` after `pip install -rrequirements.txt` in a py3 venv)
- [x] pass tests running using python3
- [x] pass CWL conformance tests using python3

**Comment by manu-chroma** [comment]
Regarding use of avro-python3 and it's compatibility with python 2:  
- https://issues.apache.org/jira/browse/AVRO-1788
- https://github.com/apache/avro/pull/133

**Comment by mr-c** [comment]
We should consider signing the http://www.python3statement.org/

**Comment by manu-chroma** [comment]
@mr-c can you highlight some of the reasons why the codebase is currently incompatible with windows?

I'm tried setting up ``schema_salad`` in windows environment and tried running some tests which were mostly failing.

**Comment by mr-c** [comment]
@manu-chroma I don't have access to MS Windows myself so the incompatibility is due to not being targeted nor tested.

**Comment by AleksandrSl** [comment]
@mr-c Is there a way I can help with this issue?

**Comment by mr-c** [comment]
Hello @AleksandrSl, thank you for your offer.

All contributions are welcome -- though we do have pending Google Summer of Code applications on this topic.

**Comment by tetron** [comment]
See https://github.com/common-workflow-language/schema_salad/pull/109#issuecomment-303397868

**Comment by manu-chroma** [comment]
It seems apt to close this issue now, since we've released a Python 3 compatible version on ``pypi`` and integrated Python 3 in all our tests. I have opened an issue regarding ``avro`` package for reference in the future: https://github.com/common-workflow-language/cwltool/issues/524

Thank you, everyone, for your efforts. :)
