### ISSUE TITLE
Lots of keyerrors

### ISSUE THREAD

**Issue by bayjan** [common-workflow-language/cwltool#327]
When I run the first example (2.1 at **http://www.commonwl.org/v1.0/UserGuide.html** ) I got lots of keyerrors and then it finally it finishes and informs that the pipeline was run successfully. The same errors also occur in cwltoil (from Toil python package). 
The very first keyerror occurs in function load_schema in line `metactx = schema_metadata.get("@context", {}) `(currently at line 191) of the file  **cwltool/cwltool/schemas/v1.0/salad/schema_salad/schema.py**
And I think the rest of the keyerrors with at least 10 keyerrors occur two lines after at line     `(schema_ctx, rdfs) = jsonld_context.salad_to_jsonld_context( schema_doc, metactx) `and as it is seen in this line a function salad_to_jsonld_context from the module  **cwltool/cwltool/schemas/v1.0/salad/schema_salad/jsonld_context.py** is called. And in this function keyerror occurs within the following for loop:
```
for t in j:
    process_type(t, g, context, defaultBase, namespaces, defaultPrefix)
```
It doesn't seem to be an error in the user guide introduction, because I also tried with the echo.cwl from the tests folder of this repository. I have installed cwltool using conda's bioconda channel and here are their versions:

> cwltest                   1.0.20170214185319          py27_0    bioconda
> cwltool                   1.0.20170217172322          py27_0    bioconda

cwltool was installed with its dependencies on a separate virual environment.
Thank you.

**Comment by mr-c** [comment]
Hello @bayjan 

Thank you for reporting your issue. 

The bioconda packages were not created by us, nor tested by us. Using `virtualenv` and `pip install cwltool==1.0.20170217172322` I was unable to reproduce your experience.

However I did install conda just now and I was able to see the same `keyerror`s you report.

Therefore this is an error in bioconda's packaging, looks like https://github.com/bioconda/bioconda-recipes/issues is the best place to report that.

Best of luck -- in the mean time you can use a `virtualenv`.

**Comment by bayjan** [comment]
Hi @mr-c ,
Thanks a lot for your very quick answer and rapidly solving this issue. Solution was so fast, because when I searched for my question like an hour after posting it, it was gone from open issues. Really fast.
Indeed it was a conda problem. I can confirm it. I had just tried it with virtualenv and pip and everything is working fine now.
