### ISSUE TITLE
make coverage.html; make coverage-report fails 

### ISSUE THREAD

**Issue by manu-chroma** [common-workflow-language/cwltool#334]
``` bash
make coverage.html 
make coverage-report fails 
```
these commands fail due to the following error: 
``` bash
Finished processing dependencies for cwltool==1.0.20170309164828
export COVERAGE_PROCESS_START=/home/manu/github/cwltool/.coveragerc; \
       cd ; ./run_test.sh RUNNER=cwltool
/bin/sh: 2: ./run_test.sh: not found
Makefile:110: recipe for target '.coverage' failed
make: *** [.coverage] Error 127
```

related line of code in makefile: https://github.com/common-workflow-language/cwltool/blob/master/Makefile#L111

**Comment by manu-chroma** [comment]
I'm interested in knowing if there is any way to access the test coverage of the current codebase.

**Comment by manu-chroma** [comment]
@mr-c thoughts ?

**Comment by mr-c** [comment]
@manu-chroma `run-test.sh` is from https://github.com/common-workflow-language/common-workflow-language/ -- the Makefile should be clarified -- sorry!

**Comment by manu-chroma** [comment]
@mr-c thanks. I will try this. :+1: 

Last night only did I realize that we can run ``conformance tests`` locally. They already present in ``cwltool/cwltool/schemas`` directory. 

I believe this is something that should be briefly mentioned in the main README. I was under the impression that they were only setup on the jenkins server. I'd be happy to make a PR for the same.

**Comment by mr-c** [comment]
You've touched on an organizational problem we have, I've started to think about it out loud at https://github.com/common-workflow-language/common-workflow-language/issues/413

In summary, please don't use the conformance tests inside `cwltool/cwltool/schemas` as they are out of date :-)

**Comment by mr-c** [comment]
Yes, we should explain how to run the conformance tests in the README -- PR gladly accepted

**Comment by manu-chroma** [comment]
> In summary, please don't use the conformance tests inside cwltool/cwltool/schemas as they are out of date :-)

@mr-c thanks for pointing this out. I was using them yesterday while debugging my PR: https://github.com/common-workflow-language/cwltool/pull/337

> Yes, we should explain how to run the conformance tests in the README -- PR gladly accepted

I'm thinking of adding short description on running ``tox`` locally. And adding essential contents from https://github.com/common-workflow-language/cwltool/blob/master/cwltool/schemas/CONFORMANCE_TESTS.md

**Comment by manu-chroma** [comment]
I was able to get combined code coverage from unit tests and conformance tests. Here it is. Conformance Tests cover roughly 30% of the codebase which is a subset of the codebase covered by unit tests. So combining the code coverage did not increase the coverage by more than few lines of code.

![image](https://user-images.githubusercontent.com/12952080/27262904-fd4b39ae-547d-11e7-92a3-7be1ef73d2a2.png)

**Comment by mr-c** [comment]
- [ ] make a simple shell script: `coverage run cwltool $@` and pass that path in as the `RUNNER` to gather test coverage from the conformance tests

**Comment by manu-chroma** [comment]
@mr-c little-confused here. I've created coverage.sh as: ```coverage run cwltool $@```

How to integrate it here: https://github.com/common-workflow-language/cwltool/blob/master/Makefile#L117
I forgot what trick you told to make the ``RUNNER`` resolve correctly.

**Comment by mr-c** [comment]
@manu-chroma  Did you try `RUNNER=path/to/coverage.sh` ?

**Comment by manu-chroma** [comment]
Yes. It's giving error in ``run_test.sh``:

Bottom of the error message: 
```
export COVERAGE_PROCESS_START=/home/manu/github/cwltool/.coveragerc; \
       cd common-workflow-language; ./run_test.sh RUNNER="/home/manu/github/cwltool/coverage.sh"
run_test.sh: Run common workflow tool description language conformance tests.

Syntax:
        run_test.sh [RUNNER=/path/to/cwl-runner] [DRAFT=cwl-draft-version]

Options:
  -nT   Run a specific test.
  -l    List tests

runner '/home/manu/github/cwltool/coverage.sh' not found
Makefile:116: recipe for target '.coverage' failed
make: *** [.coverage] Error 1
```

Going into this loop:

``` bash
if ! runner="$(which $RUNNER)" ; then
    echo >&2 "$helpmessage"
    echo >&2
    echo >&2 "runner '$RUNNER' not found"
    exit 1
fi
```

**Comment by mr-c** [comment]
Ah, it expects it to be on the PATH. Then try 
```
export COVERAGE_PROCESS_START=/home/manu/github/cwltool/.coveragerc; export PATH=$PATH:$PWD; \
       cd common-workflow-language; ./run_test.sh RUNNER=coverage.sh
```

**Comment by manu-chroma** [comment]
Updating PATH is breaking ``run_test.sh``. Not sure why 

``` bash
Using /home/manu/github/cwltool/venv3/lib/python3.5/site-packages
Finished processing dependencies for cwltool==1.0.20170811195303
export COVERAGE_PROCESS_START=/home/manu/github/cwltool/.coveragerc; export PATH=ATH:WD; \
       cd common-workflow-language; ./run_test.sh RUNNER=coverage.sh
./run_test.sh: line 3: basename: command not found
./run_test.sh: line 3: basename: command not found
./run_test.sh: line 18: uname: command not found
./run_test.sh: line 47: cut: command not found
./run_test.sh: line 47: cut: command not found
./run_test.sh: line 47: =: command not found
./run_test.sh: line 52: which: command not found
: Run common workflow tool description language conformance tests.

Syntax:
         [RUNNER=/path/to/cwl-runner] [DRAFT=cwl-draft-version]

Options:
  -nT   Run a specific test.
  -l    List tests

runner 'cwl-runner' not found
Makefile:116: recipe for target '.coverage' failed
make: *** [.coverage] Error 1
(venv3) manu@hp:~/github/cwltool$ which cwl-runer
(venv3) manu@hp:~/github/cwltool$ which cwl-runner 
/home/manu/github/cwltool/venv3/bin/cwl-runner
```

**Comment by mr-c** [comment]
Ah, if you're in a Makefile the `$` have to be escaped: `export PATH=$$PATH:$$PWD; `

**Comment by manu-chroma** [comment]
ok, PATH behavior is fine now. But it shows coverage.sh as invalid runner
```
 COVERAGE_PROCESS_START=/home/manu/github/cwltool/.coveragerc; export PATH=$PATH:$PWD; \
       cd common-workflow-language; ./run_test.sh RUNNER=coverage.sh
run_test.sh: Run common workflow tool description language conformance tests.

Syntax:
        run_test.sh [RUNNER=/path/to/cwl-runner] [DRAFT=cwl-draft-version]

Options:
  -nT   Run a specific test.
  -l    List tests

runner 'coverage.sh' not found
Makefile:116: recipe for target '.coverage' failed
make: *** [.coverage] Error 1
```

**Comment by mr-c** [comment]
Is it marked executable? `chmod a+x script.sh`

**Comment by manu-chroma** [comment]
ok, added that. Output now: 
```
Using /home/manu/github/cwltool/venv3/lib/python3.5/site-packages
Finished processing dependencies for cwltool==1.0.20170811195303
export COVERAGE_PROCESS_START=/home/manu/github/cwltool/.coveragerc; export PATH=$PATH:$PWD; \
       cd common-workflow-language; ./run_test.sh RUNNER=coverage.sh
--- Running conformance test v1.0 on /home/manu/github/cwltool/coverage.sh ---
No file to run: 'cwltool'
```

**Comment by mr-c** [comment]
I would debug this by using `coverage.sh` by hand as if it were `cwltool`

**Comment by manu-chroma** [comment]
@mr-c Can you address this [issue](https://github.com/common-workflow-language/cwltool/issues/119#issuecomment-321996977)?

**Comment by mr-c** [comment]
@manu-chroma What happens when you run a single conformance test directly by hand with `coverage.sh` (without using run_test.sh or cwltest)?

**Comment by manu-chroma** [comment]
```(venv3) manu@hp:~/.../common-workflow-language/v1.0$ coverage.sh --debug --outdir=/tmp/tmprcwzi_kf v1.0/scatter-wf1.cwl v1.0/scatter-job1.json```

This runs successfully. Trying to debug for the whole suite. 

Also, I had modified ``coverage.sh`` to: 
```
coverage run /home/manu/github/cwltool/venv3/bin/cwltool $@
```

Should use ``readlink cwltool`` here I suppose

**Comment by manu-chroma** [comment]
@mr-c Working now. Need to remove hardcoded paths though  
```
(venv) manu@hp:~/.../cwltool/common-workflow-language$ coverage report --omit="*/site-packages/*","*/schema_salad/*"
Name                                                         Stmts   Miss  Cover
--------------------------------------------------------------------------------
/home/manu/github/cwltool/cwltool.py                             5      0   100%
/home/manu/github/cwltool/cwltool/__init__.py                    2      0   100%
/home/manu/github/cwltool/cwltool/builder.py                   190    163    14%
/home/manu/github/cwltool/cwltool/cwlrdf.py                     84     71    15%
/home/manu/github/cwltool/cwltool/docker.py                     99     85    14%
/home/manu/github/cwltool/cwltool/docker_id.py                  46     32    30%
/home/manu/github/cwltool/cwltool/draft2tool.py                476    424    11%
/home/manu/github/cwltool/cwltool/errors.py                      4      0   100%
/home/manu/github/cwltool/cwltool/expression.py                174    144    17%
/home/manu/github/cwltool/cwltool/flatten.py                    19     16    16%
/home/manu/github/cwltool/cwltool/job.py                       314    274    13%
/home/manu/github/cwltool/cwltool/load_tool.py                 151    124    18%
/home/manu/github/cwltool/cwltool/main.py                      560    395    29%
/home/manu/github/cwltool/cwltool/mutation.py                   37     25    32%
/home/manu/github/cwltool/cwltool/pack.py                      125    112    10%
/home/manu/github/cwltool/cwltool/pathmapper.py                175    135    23%
/home/manu/github/cwltool/cwltool/process.py                   548    466    15%
/home/manu/github/cwltool/cwltool/resolver.py                   40     30    25%
/home/manu/github/cwltool/cwltool/sandboxjs.py                 211    185    12%
/home/manu/github/cwltool/cwltool/software_requirements.py      74     53    28%
/home/manu/github/cwltool/cwltool/stdfsaccess.py                51     25    51%
/home/manu/github/cwltool/cwltool/update.py                    377    329    13%
/home/manu/github/cwltool/cwltool/utils.py                     104     84    19%
/home/manu/github/cwltool/cwltool/workflow.py                  635    575     9%
--------------------------------------------------------------------------------
TOTAL                                                         4501   3747    17%
```
