### ISSUE TITLE
MS Windows comptabilitiy

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#340]

**Comment by manu-chroma** [comment]
Can we consider using ``Bash on Ubuntu on Windwos`` 
https://msdn.microsoft.com/en-us/commandline/wsl/about

I was able to successfully setup and get all passing tests for ``cwltool`` and ``schema_salad`` on bash running inside my Windows environment. 
I think this might be a great option which can be considered. The fact that almost no changes are required in the codebase and we're able to run ``cwltool`` is a great. 

My only concern is the integration of docker in this approach. I'd love to discuss this approach in detail with the community.

**Comment by manu-chroma** [comment]
Passing tests on windows: 😄 
![image](https://cloud.githubusercontent.com/assets/12952080/24157685/17862f3e-0e80-11e7-9103-941455c78774.png)

**Comment by kapilkd13** [comment]
Hi. It's a great idea @manu-chroma . Only catch is  `Bash on Ubuntu on windows` is available for windows 10. To use Bash and *NIX tools on previous version we have to go to utilities like `cygwin`. 
About integration with docker, unfortunately Travis CI/CD still doesn't support docker under Windows.
According to me we can go with `Appveyor CI`. It is a travis alternative for windows. And It support open-source repositories like our's for free. https://packaging.python.org/appveyor/ is a great place if we want to use Appveyor. 
Other than that we may use Jenkins CI for windows if we have access to windows machine that we can set as a slave. But I liked idea of `Appveyor`. @mr-c What are your views on it.

**Comment by mr-c** [comment]
Hello all, thank you for providing your ideas; very cool to see that `cwltool` passes the tests using the Linux subsystem for Windows 10.

As Python has native support for MS Windows, so it should be possible to get `cwltool` working without resorting to the Linux subsystem or cygwin.

Appveyor CI is what I was hinting at should be used for Windows CI, yep.

**Comment by bpmweel** [comment]
Hey All,

Having windows support would be great. I'm working on a project with a research group that handles clinical data. All the hospitals they work with use windows servers and are very very hesitant to adopt linux.

In order to run some workflows to process the clinical data at the hospital supplied servers we would need cwltool to run under windows server 2013 for instance.

**Comment by jvdzwaan** [comment]
I'm also interested in Windows support for CWL. The project I'm working on is about text mining on  privacy sensitive data. So, preferably, the workflows we are developing should be able to run on researchers' personal computers and these mostly are Windows computers.

**Comment by undu** [comment]
From my small effort (and @tetron's cleanup) paths should be handled correctly under Windows.

What was missing back then:
1. Symbolic link creation (not native in Python 2, but native in Python 3.3 onward through os.symlink)
2. Use a fallback strategy to share outputs when symlinking is not possible, e.g. copy files.

I don't know if there was any progress towards this in the meantime.

**Comment by manu-chroma** [comment]
@kapilkd13 probably you can close this one now? :smile:

**Comment by kapilkd13** [comment]
Closing, as we now have windows compatible cwltool.
