### ISSUE TITLE
cwlVersion: v0.1 gives a bad user experience

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#341]
```
(env) michael@dan:~/workshop$ cwl-runner echo.cwl --help
/home/michael/workshop/env/bin/cwl-runner 1.0.20170309164828
Resolved 'echo.cwl' to 'file:///home/michael/workshop/echo.cwl'
Tool definition failed initialization:
('https://w3id.org/cwl/CommonWorkflowLanguage.yml', HTTPError(u'404 Client Error: Not Found for url: https://w3id.org/cwl/CommonWorkflowLanguage.yml',))
```

**Comment by mr-c** [comment]
There should be no downloading if the version isn't on the list -- in case of an unknown version the list of acceptable versions should be displayed

**Comment by manu-chroma** [comment]
[cwl v0.1 is still listed on pypi.](https://pypi.python.org/simple/cwltool/) 
A good step would be to take this particular release down.   

Oldest github tag release is v1.0.2: https://github.com/common-workflow-language/cwltool/tree/v1.0.20160810200423 so no problem there

**Comment by mr-c** [comment]
FYI: this is about `cwlVersion: v0.1` as a typo for `cwlVersion: v1.0` inside a CWL file

**Comment by manu-chroma** [comment]
oh. very sorry. I completely misunderstood this issue.

**Comment by mr-c** [comment]
No worries :-) Your response helped me be more clear.
