### ISSUE TITLE
cwltool fails in git bash

### ISSUE THREAD

**Issue by hmenager** [common-workflow-language/cwltool#344]
reporting this for @am-cornelis
trying to run cwltool in git bash (on Windows) fails when trying to create a symlink.

I'm pasting below the extensive bug report she sent me:

At the ELIXIR All Hands - CWL workshop, I came across the following
error message, which you wanted to hear about.

I was running the cwl-runner on windows using git bash:

```
$ cwl-runner helloworld.cwl input.yaml
C:\Apps\Python27\Scripts\cwl-runner 1.0.20170309164828
Resolved 'helloworld.cwl' to
'file:///C:/src/play/cwl-workshop/helloworld.cwl'
Got workflow error
Traceback (most recent call last):
  File "c:\apps\python27\lib\site-packages\cwltool\main.py", line 230,
in single_job_executor
    r.run(**kwargs)
  File "c:\apps\python27\lib\site-packages\cwltool\job.py", line 213, in run
    stageFiles(self.pathmapper, os.symlink, ignoreWritable=True)
AttributeError: 'module' object has no attribute 'symlink'
Workflow error, try again with --debug for more information:
'module' object has no attribute 'symlink'
```

This is my setup:

Windows 10 Pro, with Git Bash (2.7.0)

```
$ python --version
Python 2.7.11

$ pip --version
pip 7.1.2 from c:\apps\python27\lib\site-packages (python 2.7)

$ cwl-runner --version
C:\Apps\Python27\Scripts\cwl-runner 1.0.20170309164828
```
Cheers,
Amélie

**Comment by am-cornelis** [comment]
If it helps reproduce the error: here are the 2 files I was using...

[cwl-workshop.zip](https://github.com/common-workflow-language/cwltool/files/864551/cwl-workshop.zip)

**helloworld.cwl**
``` 
#!/usr/bin/env cwl-runner
 
 cwlVersion: v1.0
 class: CommandLineTool
 
 inputs:
   message: string
 
 baseCommand: [ echo ]
 
 outputs:
   response: stdout
```

**input.yaml**
```
message: "Bonjour, Monde"
```

**Comment by xamgore** [comment]
The same issue with symlink:

```
Got workflow error
Traceback (most recent call last):
  File "c:\users\mi\downloads\cwl\venv\lib\site-packages\cwltool\main.py", line 251, in single_job_executor
    r.run(**kwargs)
  File "c:\users\mi\downloads\cwl\venv\lib\site-packages\cwltool\job.py", line 275, in run
    stageFiles(self.pathmapper, os.symlink, ignoreWritable=True)
AttributeError: 'module' object has no attribute 'symlink'
Workflow error, try again with --debug for more information:
'module' object has no attribute 'symlink'
```

I will try the [solution-from-google](https://github.com/gcodeforks/apptrace/issues/8#issuecomment-94408004) tomorrow.

**Comment by tetron** [comment]
Windows support is being worked on here: https://github.com/common-workflow-language/cwltool/pull/419

**Comment by manu-chroma** [comment]
cc: @kapilkd13

**Comment by kapilkd13** [comment]
Hi @xamgore @am-cornelis We have made cwltool compatible with windows with the latest release. You can try it by updating your cwltool. Just to clarify, you won't need to use git bash, command prompt would work :smiley: . Documentation on windows usage is currently in this PR https://github.com/common-workflow-language/cwltool/pull/486

**Comment by manu-chroma** [comment]
I'm closing this issue now -- @hmenager @am-cornelis. 

@kapilkd13 has already provided all the relevant details.
