### ISSUE TITLE
Suggestion to allow a choice of md5 checksum

### ISSUE THREAD

**Issue by kmhernan** [common-workflow-language/cwltool#371]
Due to the development environment I currently work with, I need to use md5 checksums. It would be great if I could choose this as an option for cwltool (I can do this in the rabix tool) so I could simply parse the JSON stdout from my workflows.

**Comment by mr-c** [comment]
Hey @kmhernan 

That'd require a change to the specification, as [only `sha1` is defined as valid](http://www.commonwl.org/v1.0/CommandLineTool.html#File). You are welcome to fork `cwltool` to add this feature.

**Comment by kmhernan** [comment]
@mr-c thanks for the response! I understand 😄

**Comment by manu-chroma** [comment]
@mr-c can we close this one?
