### ISSUE TITLE
deciding most appropriate path for windows compatibility for cwltool and schema-salad

### ISSUE THREAD

**Issue by kapilkd13** [common-workflow-language/cwltool#390]
Hi As I would be working on windows compatibility, I need some help :smiley:   
Current understanding according to me:  
1. Some of our `CommandLineTool` uses `baseCommand` like `echo` and `cat`. These are unix tools only available in linux system.  
2. We can run Linux container on a windows 10 machine. https://stefanscherer.github.io/run-linux-and-windows-containers-on-windows-10/
3. Docker support for windows server is only from windows server 2016 onwards. https://blog.docker.com/2016/09/dockerforws2016/

 For us providing windows support means, a user can develop a workflow on his windows machine. On `run` if the workflow uses unix utilities/tools, then in that case these workflow should run in a Linux docker container or alternatively we can make it default that all workflows should run in a  Linux container. 
We will be using Appveyor CI for testing and as some of our unit tests uses unix tools like `cat` on testing, I guess we need to provide a Linux container where they can use these tools.
Appveyor has a Visual Studio 2017 image(runs windows server 2016) and [supports docker](https://www.appveyor.com/docs/build-environment/)  But as I read somewhere this Docker support only applies to windows containers and not Linux Containers. I raised a [issue](http://help.appveyor.com/discussions/questions/4051-creating-linux-docker-container-inside-windows-server-2016-visual-studio-2017-image) with appveyor to confirm it.  
I also found a `Linuxkit for windows` released last month that should allow [linux container on windows server 2016](https://thenewstack.io/finally-linux-containers-really-will-run-windows-linuxkit/) but I am not sure if Appveyor already supports it or not.  
So if you have any idea how else we can test these builds, that would be awesome.  
In the meantime what I am can do is, setup docker and linux container on my windows machine. Start working on other issues that are preventing us from windows support and for running test cases, use `--default-container` flag to generate a linux container and run test cases there. 
I talked to Janneke, she is one of my mentor and potential user of windows support and for her use case running workflows in a linux container on windows machine is good.

**Comment by mr-c** [comment]
Docker is available for Microsoft Windows 10 Professional or Enterprise 64-bit  at https://www.docker.com/docker-windows and previous versions of Docker support other versions of Microsoft Windows like Windows 10 Education (1511 November update, Build 10586 or later): https://docs.docker.com/v1.13/docker-for-windows/install/#what-to-know-before-you-install

**Comment by mr-c** [comment]
@kapilkd13 can you test appveyor in a separate GitHub repository where you instruct them to run docker commands to see what happens?

**Comment by kapilkd13** [comment]
I will try that.

**Comment by psafont** [comment]
If people want to run those commands natively, there are unix tools packages like [cygwin](https://www.cygwin.com/) or [git for windows](https://git-for-windows.github.io/).

Consider recommending their installation (or other tools that integrate them, like [cmder](http://cmder.net/)) to access unix tools.

Nowadays Windows 10 allows to run Linux executables through a compatibility layer (like WINE), but it doesn't work on older Windows, I haven't personally tried it: https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by mr-c** [comment]
Thank you @psafont for the assistance. This is usecase is all about using Linux Docker containers under windows and nothing more, anything else is too complicated and fragile :-)

**Comment by psafont** [comment]
I agree it's probably too complicated and fragile.

I don't know if that will deter every single user from trying to run the workflows natively anyway ;)

**Comment by mr-c** [comment]
@psafont Yep, we'll probably make a Debian stable image the default under windows and provide a friendly but firm error message if Docker isn't available

**Comment by kapilkd13** [comment]
Hi @mr-c  I tried running docker on appveyor's 2017 image.  
First I tried windows image to check if docker is working
![screenshot from 2017-05-24 23-41-15](https://cloud.githubusercontent.com/assets/8131630/26418744/035e55bc-40db-11e7-970d-520fc715e23a.png) and it built succesfully  

But when I tried building `debian` image it failed with `image operating system "linux" cannot be used on this platform` :disappointed: 
![screenshot from 2017-05-24 23-40-33](https://cloud.githubusercontent.com/assets/8131630/26418791/2befd88e-40db-11e7-9594-4b213f8ac32b.png)

**Comment by mr-c** [comment]
Thanks for the update -- how about using an existing Linux image instead of building one?

`docker run -it debian` or similar

**Comment by mr-c** [comment]
By the way, if you adjust the permissions at https://ci.appveyor.com/project/kapilk/testDocker/settings/permissions you can share links to the appveyor output

**Comment by kapilkd13** [comment]
Hi I didn't knew if link would give you access to logs. Thanks. Here is the link https://ci.appveyor.com/project/kapilkd13/testdocker/history  Also I tried using existing Linux image, but I guess the problem is Appveyor's windows engine has only two base image `microsoft/windowsservercore` and `microsoft/nanoserver`

**Comment by mr-c** [comment]
@kapilkd13 Okay, then we will have to restrict our usage of appveyor to non-docker & non-unix tests for now.

**Comment by kapilkd13** [comment]
Okay. We can do that. Also I found a interesting read here https://redmondmag.com/articles/2017/04/20/windows-server-2016-getting-linux-containers.aspx So I guess in future we would be able to do these tests once Appveyor adapts to these changes. Till then I will ping them once in a while :smiley_cat:

**Comment by mr-c** [comment]
Appveyor could support Linux Docker containers on Microsoft Windows today the same way regular users can run Linux Docker containers on Microsoft Windows today: https://docs.docker.com/machine/overview/ :-)

**Comment by mr-c** [comment]
(or by using Docker for Windows on newer Microsoft Windows versions: https://docs.docker.com/docker-for-windows/ )

**Comment by kapilkd13** [comment]
So maybe they are doing it on purpose. For Now I will start working with Schema-salad for windows compatibility.

**Comment by kapilkd13** [comment]
Thanks to all for helping. :smile: 
Now cwltool and Schema salad is Windows Compatible.
