### ISSUE TITLE
Need to add CWL Build Bot to PyPI maintainer list

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#4]
@tetron can you add the PyPI user `common_workflow_language` to the PyPI listings?

**Comment by manu-chroma** [comment]
@mr-c 
hey, what's the status on this issue?

**Comment by manu-chroma** [comment]
@mr-c sorry for pinging twice. 

can you confirm the status of this one too?

**Comment by mr-c** [comment]
@manu-chroma we decided in favor of manual releases, though those still need to be automated
