### ISSUE TITLE
In Docker Hub repository, there are no description where docker image for cwltool comes from

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/cwltool#400]
`cwltool` is also published as a Docker container in [Docker Hub]( https://hub.docker.com/r/commonworkflowlanguage/cwltool/) but there are no descriptions in the repository where this image comes from.

It would be helpful if there is a description that published Docker image is made by [Jenkins](https://ci.commonwl.org/job/cwltool-conformance/) server when `cwltool` passes conformance tests.

**Comment by mr-c** [comment]
Thank you @tom-tan for the report. 

I'm not a Docker expert, right now the publication is kicked off via
```
./build-cwl-docker.sh && docker push commonworkflowlanguage/cwltool_module && docker push commonworkflowlanguage/cwltool
```
Assistance with how to modify that invocation (or files in this repo) would be appreciated :-)

**Comment by tom-tan** [comment]
Thank you for your quick reply!

This is just a documentation issue in Docker Hub page.

Docker Hub repository for `cwltool` does not describe why it is not built by automated built.

If there is a description how it is built and pushed, it is OK for me.
For instance:

> This image is built by [Jenkins](https://ci.commonwl.org/job/cwltool-conformance/) server when it passes conformance tests.

I made this issue instead of a pull request because I do not know how to make a pull request to fix full description in Docker Hub repository.

**Comment by mr-c** [comment]
Got it, I've added the text you suggested to https://hub.docker.com/r/commonworkflowlanguage/cwltool/ -- thanks!

**Comment by tom-tan** [comment]
Thanks!
