### ISSUE TITLE
update README's test execution instructions

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#401]
basically:
`pip install tox; tox`

**Comment by psafont** [comment]
How is it different from running the current command? (`python setup.py test`)

**Comment by manu-chroma** [comment]
@psafont tox does ``pip install requirements`` before calling ``setup.py test``

**Comment by manu-chroma** [comment]
and another added benefit is it creates fresh virtual environment

**Comment by manu-chroma** [comment]
does it make sense to move the tests instruction in ``CONTRIBUTING.md`` rather than having them in ``README``?

**Comment by manu-chroma** [comment]
@mr-c can we do detox? really speeds up the testing 
```
pip install detox; detox
```

**Comment by mr-c** [comment]
Neat, I've never seen that before. That can go as an additional option.

**Comment by manu-chroma** [comment]
Yeah, just a wrapper around tox :smile: 

https://github.com/tox-dev/detox#what-is-detox
