### ISSUE TITLE
draft-2 support: fix or remove?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#441]
sometime in the last month (it's been that long since we had a new release) `cwltool` no longer works with draft-2:

https://ci.commonwl.org/job/cwltool-conformance/290/console

Shall we fix it or remove it?

**Comment by mr-c** [comment]
`git bisect` on schema_salad shows the breakage for `draft-2` was introduced in https://github.com/common-workflow-language/schema_salad/commit/8a6eaff53eadca000a2c40624b355d83d89f6656

**Comment by mr-c** [comment]
I removed draft-2 support from the conformance tests so we should proceed with removing it from the reference implementation.

**Comment by kapilkd13** [comment]
Is there some organization who still have workflows that use `draft-2`.

**Comment by anton-khodak** [comment]
Closed in #520
