### ISSUE TITLE
Error: ContextualVersionConflict ruamel/schema-salad

### ISSUE THREAD

**Issue by johnbradley** [common-workflow-language/cwltool#449]
## Expected Behavior
cwltool should run and show command line usage

## Actual Behavior
cwltool fails with this error:
```
pkg_resources.ContextualVersionConflict: (ruamel.yaml 0.15.15  (/tmp/env/lib/python2.7/site-packages),  Requirement.parse('ruamel.yaml<=0.15.2,>=0.12.4'), set(['schema-salad']))
```

## Workflow Code
```
virtualenv env
source env/bin/activate
pip install --upgrade cwltool
cwltool
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/tmp/env/bin/cwltool", line 11, in <module>
    sys.exit(main())
  File "/tmp/env/local/lib/python2.7/site-packages/cwltool/main.py", line 661, in main
    _logger.info(versionfunc())
  File "/tmp/env/local/lib/python2.7/site-packages/cwltool/main.py", line 574, in versionstring
    pkg = pkg_resources.require("cwltool")
  File "/tmp/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/tmp/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ruamel.yaml 0.15.15 (/tmp/env/lib/python2.7/site-packages), Requirement.parse('ruamel.yaml<=0.15.2,>=0.12.4'), set(['schema-salad']))
```

## Your Environment
Tried on both macos and Ubuntu 16.04.1 LTS
* cwltool version: fails with the same error.

## Notes:
If I do this first everything works fine:
```
pip install ruamel.yaml==0.15.2
```

**Comment by manu-chroma** [comment]
Thanks for reporting. 
I've created a patch that should take care of this: https://github.com/common-workflow-language/cwltool/pull/450

**Comment by Unode** [comment]
Is a quickfix going to be released sometime soon?
We are also seeing [test failures](https://travis-ci.org/luispedro/ngless#L2253) due to this.

**Comment by mr-c** [comment]
Hello all, I've made new `cwltool` and `schema_salad` releases -- please let me know if the issue is resolved. Our apologies for the inconvenience.

**Comment by Unode** [comment]
Back to green on our side. Thanks for the quick action.

**Comment by mr-c** [comment]
Thanks for the update @Unode , and again my apologies. Thank you @johnbradley for the report.
