### ISSUE TITLE
support  --net option for docker

### ISSUE THREAD

**Issue by philloooo** [common-workflow-language/cwltool#48]
[This](https://github.com/common-workflow-language/cwltool/commit/f0487153700af34f34d1344d88df5e88b853eb4c) enforces to not use any network for docker. Can you support user passing network to use and default to `none`?

**Comment by mr-c** [comment]
Hello @philloooo & thank you for filling this issue. My apologies for not responding sooner. I believe we have addressed you request in https://github.com/common-workflow-language/cwltool/pull/64. Feel free to re-open this if that isn't working for you.
