### ISSUE TITLE
Packed workflow missing cwlVersion- Not runnable

### ISSUE THREAD

**Issue by FarahZKhan** [common-workflow-language/cwltool#482]
## Expected Behavior
After running `cwltool --pack hello-params.cwl params.yaml`, the resulting file should be executable. 

## Actual Behavior
It did not work and generated error below: 
```
Resolved 'pack-version.cwl' to 'file:///Users/farahkhan/Desktop/provenance-cwl/cwltool/example-workflows/workflows/workflows/hello/pack-version.cwl'
No cwlVersion found, treating this file as draft-2.
```
If we add the object `"cwlVersion": "v1.0",` manually, the problem is solved.
## Workflow Code
https://github.com/common-workflow-language/workflows/tree/master/workflows/hello

## Your Environment
* cwltool version: 1.0.20170719004811

**Comment by kapilkd13** [comment]
Hi @FarahZKhan I can verify the behaviour you noticed.
This is Interesting, If I remember correctly usually when cwltool can't find a cwlversion mentioned it treat it as version 1. This looks like a recent change. Maybe a policy change to impose a explicit `cwlversion` mention. Your thoughts @mr-c

**Comment by mr-c** [comment]
We should be explicitly adding `cwlVersion: v1.0` if it is missing, yes

**Comment by manu-chroma** [comment]
@FarahZKhan As mentioned in your traceback, we were falling to ``draft-2`` when no version was found. 
https://github.com/common-workflow-language/cwltool/pull/491 should fix it.

**Comment by mr-c** [comment]
To say this another way: `cwlVersion` is required to be present in all CWL descriptions. The output of `cwltool --pack` needs to propagate that `cwlVersion` main description to the packed output description.

**Comment by FarahZKhan** [comment]
Thanks for working on this @manu-chroma I will test and let you know. 
Cheers,

**Comment by manu-chroma** [comment]
When creating ``pack`` dict why are we not putting ``"cwlVersion": metadata["cwlVersion"]`` inside ``"$graph": []``
Reference line: https://github.com/common-workflow-language/cwltool/blob/master/cwltool/pack.py#L129

**Comment by mr-c** [comment]
@manu-chroma looks like that gets deleted at https://github.com/common-workflow-language/cwltool/blob/master/cwltool/pack.py#L148 -- so the L129 parts about `cwlVersion` need to happen after L148
