### ISSUE TITLE
[Windows] clarify Python 3 support

### ISSUE THREAD

**Issue by manu-chroma** [common-workflow-language/cwltool#500]
In Windows installation docs we've specified that we support Python 2 and 3. https://github.com/common-workflow-language/cwltool/blob/master/windowsdoc.md#requirements

But we're not testing Python 3 on ``appveyor``. We should either remove Python 3 from the docs or add Python 3 in the ``appveyor`` testing.

**Comment by kapilkd13** [comment]
I will add python 3 to appveyor. That will be better option.

**Comment by mr-c** [comment]
@manu-chroma thanks for catching this and @kapilkd13 thanks for fixing it :-)
