### ISSUE TITLE
cwltool specific hint that a particular step/Process shouldn't be cached

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#522]

**Comment by tetron** [comment]
There's an Arvados requirement that specifies this:

http://doc.arvados.org/user/cwl/cwl-extensions.html  `arv:ReuseRequirement`

I'm pretty sure we want to add this to a future iteration of the spec, but consider adopting the Arvados-namespaced one for now to reduce the proliferation of terms?

**Comment by mr-c** [comment]
@tetron Great news, I agree we should use the Arvados term for now

**Comment by mr-c** [comment]
This was already implemented as https://www.commonwl.org/v1.1/Workflow.html#WorkReuse
