### ISSUE TITLE
Avro workaround in Python 3

### ISSUE THREAD

**Issue by manu-chroma** [common-workflow-language/cwltool#524]
This issue documents workaround to make ``avro`` package in Python 3. Might be helpful in the future. 

- ``avro`` package is an indirect dependency of ``cwltool`` (direct dependency of ``schema_salad`` tool). It has two separate versions: [Python 2](https://pypi.python.org/pypi/avro/1.8.2) and [Python 3](https://pypi.python.org/pypi/avro-python3/1.8.2). Python 2 version has worked well for us in the past.
 
- During Python 3 porting process, we found ``avro`` for Python 3 had a few bugs and didn't work well with CWL Tool even after repeated efforts. However, running ``avro-python2`` through ``2to3`` fixer and then using it in Python 3 runtime worked well with very minimal changes.
 
- We tried a lot to convince Apache Avro devs to combine Python 2 and Python 3 package. PR: https://github.com/apache/avro/pull/235, https://github.com/apache/avro/pull/234; https://github.com/apache/avro/pull/133 Discussion on JIRA: https://issues.apache.org/jira/browse/AVRO-2046, but all this effort was largely met with no response. 

- We finally forked ``avro``, modified source a little to release [``avro-cwl``](https://pypi.python.org/pypi?:action=display&name=avro-cwl), and use it with Python 3 with help of [autotranslate](http://python-future.org/translation.html) module: basically use 2to3 fixer during runtime. 
<br>
The workaround is a hack which seems to be work. There are bound to be regressions in this method. In future we can try the following options: 

- Get [this PR ](https://github.com/apache/avro/pull/234) merged, so that a single ``avro`` package is supported in both Python 2 and 3 out of the box; and no need of fixers.  
- Consider getting the above PR merged in our fork of ``avro`` and use that solution, should Apache Avro refuse to accept the patch. 

**All this was discussed in PR: https://github.com/common-workflow-language/cwltool/pull/442. Might be a useful reference.**

**Comment by westover** [comment]
I made a pull to the Avro repo which addresses some of it
https://github.com/apache/avro/pull/251

**Comment by garyluu** [comment]
Is this still an issue?  Schema Salad doesn't seem to depend on Avro anymore.

**Comment by mr-c** [comment]
@garyluu It is not, you are correct. We pulled in just the parts of Avro that we used and then made further modifications: https://github.com/common-workflow-language/schema_salad/tree/master/schema_salad/avro
