### ISSUE TITLE
unavailable method schema_salad.ref_resolver.resolve_json_pointer used

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#58]
Hello @tetron 

In https://github.com/common-workflow-language/cwltool/blob/master/cwltool/expression.py#L24 `schema_salad.ref_resolver.resolve_json_pointer` is used but this function was dropped in schema_salad on December 8th in https://github.com/common-workflow-language/schema_salad/commit/f647d86f0597961f244840c9c673470e7aa2153c#diff-ceb29e0b30c435fbee3c927af99c9f35L420

Looks like we need a test for this codepath & a fix

**Comment by tetron** [comment]
The code in expression.py should be removed.  The draft-2 json pointer expressions are now transformed into draft-3 parameter references.

**Comment by mr-c** [comment]
Yay, I love code removal!

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwltool/commit/a3d24f8da648befae983fe9f1b995713fdfcb28f#diff-cb6110fc9c5f825722db0f9c57cb1335 / #62
