### ISSUE TITLE
What to do when staging optional inputs that aren't present?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#581]
They can lead to errors. Is that a correct outcome or should they be ignored?

https://github.com/EOSC-LOFAR/presto-cwl/blob/6654cce1ee48e4a09a34551b1639f743db66f5d5/presto.cwl
https://github.com/EOSC-LOFAR/presto-cwl/blob/6654cce1ee48e4a09a34551b1639f743db66f5d5/steps/prepsubband.cwl#L9

Issue courtesy @gijzelaerr

**Comment by anton-khodak** [comment]
Moved to https://github.com/common-workflow-language/common-workflow-language/issues/617
