### ISSUE TITLE
Set default arguments in cwltool.factory.Factory

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/cwltool#596]
In the README, the recommended way to use cwltool as a factory is to use the `cwltool.factory.Factory` class (https://github.com/common-workflow-language/cwltool#import-as-a-module). However, this doesn't set default command line options - these are normally set in the command line using argparse in main by: https://github.com/common-workflow-language/cwltool/blob/f691bf1aa66f2836694716c9845731962147079b/cwltool/main.py#L756 If no default command line options are passed when instantiating the Factory, then this produces lots of unintended effects (e.g. use_container is False)

**Comment by anton-khodak** [comment]
See also https://github.com/common-workflow-language/cwltool/issues/596
