### ISSUE TITLE
Test failure from installation page

### ISSUE THREAD

**Issue by rmccole** [common-workflow-language/cwltool#615]
## Expected Behavior
Tests should complete. Tests are run using command 
`py.test --ignore cwltool/schemas/ --pyarg cwltool`

## Actual Behavior
Test failed. Output:

`==================================================== FAILURES ====================================================
__________________________________________ TestOverride.test_overrides ___________________________________________

self = <cwltool.tests.test_override.TestOverride testMethod=test_overrides>

    @pytest.mark.skipif(onWindows(),
                        reason="Instance of Cwltool is used, On windows that invoke a default docker Container")
    def test_overrides(self):
        sio = StringIO()
    
        self.assertEquals(main([get_data('tests/override/echo.cwl'),
                                get_data('tests/override/echo-job.yml')],
                               stdout=sio), 0)
>       self.assertEquals({"out": "zing hello1"}, json.loads(sio.getvalue()))
E       AssertionError: {'out': 'zing hello1'} != {u'out': u'-n zing hello1\n'}
E       - {'out': 'zing hello1'}
E       + {u'out': u'-n zing hello1\n'}
E       ?  +       + +++           ++

anaconda/envs/CWLtest/lib/python2.7/site-packages/cwltool/tests/test_override.py:26: AssertionError`

## Workflow Code
```
`py.test --ignore cwltool/schemas/ --pyarg cwltool`

```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception
Run the workflow with ``--debug`` flag for more verbose logging 
```

## Your Environment
* cwltool version: 
`cwltool 1.0.20180116213856`
Check using ``cwltool --version``
OS: Mac OS 10.12.6

**Comment by anton-khodak** [comment]
The problem is that the standard shell for building command line in cwltool is `/bin/sh` which does not support `-n ` argument to `echo` on MacOS. We can either change the default shell to `/bin/bash` for MacOS specifically or for cwltool in general. Are there specific reasons to use `/bin/sh` by default, @tetron ?

**Comment by mr-c** [comment]
@anton-khodak Good catch. I'm guessing the assumption of the availability of `-n` was an oversight. The shell needs to be a POSIX shell, so the use of `/bin/sh` is correct.

**Comment by mr-c** [comment]
@anton-khodak I think it would be fine to drop the `-n` and amend the tests to expect the newline character
