### ISSUE TITLE
Allowing directories to be assigned as a File type

### ISSUE THREAD

**Issue by kmhernan** [common-workflow-language/cwltool#65]
Hello,

It appears that cwltool no longer allows you to assign a path as a `File`, which then makes it difficult to mount a directory to the docker run. This is especially problematic for things like variant annotation software which often have a particular directory structure containing 100's of annotation files.

It seems like the commit present [here](https://github.com/common-workflow-language/cwltool/commit/893de464b3dd6f359e39ee00d8d4f69cfdb1e1bc) is potentially the culprit. This functionality worked with cwl version `1.0.20160129183049` but it definitely doesn't work in the current one. How can we handle this issue?

**Comment by mr-c** [comment]
Hello @kmhernan and thank you for your report.

This behaviour change of `cwltool` is to match the standard. Over in https://github.com/common-workflow-language/common-workflow-language/issues/172 is a great proposal from @tetron to add functionality to do what you're asking for. We would then implement it in `cwltool`.

I'm going to close this issue; please let us know in https://github.com/common-workflow-language/common-workflow-language/issues/172 if it works for you.
