### ISSUE TITLE
Extract all cwl/yml/json files involved in a workflow run

### ISSUE THREAD

**Issue by FarahZKhan** [common-workflow-language/cwltool#666]
Hello, 
I was wondering if there is any existing code snippet/structure in cwltool implementation that can help in collecting all the cwl, yaml and json files involved in a workflow run. 

If not, what is the best approach for this task? Going through keys such as `run`, `import` and extracting values? or something more efficient? 

Any help will be much appreciated,
Thanks

**Comment by tetron** [comment]
cwltool --scandeps example.cwl

Works for input documents as well.

**Comment by FarahZKhan** [comment]
Thanks for the reply Petet, I got the files using this command:
`cwltool --print-deps example.cwl` and `cwltool --print-deps job.yml` to get all the related files.
