### ISSUE TITLE
Race condition in cwltool parallel mode

### ISSUE THREAD

**Issue by adamstruck** [common-workflow-language/cwltool#689]
I have been testing the parallel mode for cwltool using the latest code on master (addcaa2) so I could remove that logic from cwl-tes.  I found through running the conformance tests that there is a race condition in the MultithreadedJobExecutor.  

The race condition is between removing the thread from the threads set and the exception being appended to the exceptions array.  I found that some portion of the time that this loop https://github.com/common-workflow-language/cwltool/blob/master/cwltool/executors.py#L170-L171 would break too early and miss an exception due to the problem described above.

**Comment by tetron** [comment]
Yes, the multithreaded executor is missing some necessary locking.

**Comment by adamstruck** [comment]
Looks like this was fixed by #800
