### ISSUE TITLE
conformance test gives "TypeError: __init__() got an unexpected keyword argument 'type'"

### ISSUE THREAD

**Issue by samuell** [common-workflow-language/cwltool#73]
I tend to get these errors with `cwltool --conformance-test`, white a bit.

One example is for the [samtools-view tool](https://github.com/common-workflow-language/workflows/blob/master/tools/samtools-view.cwl), but I suddenly got a similar error for my work on `bwa-aln.cwl`, after adding a trailing slash to a namespace (`s: http://schema.org/` instead of `s: http://schema.org`).

Any hints?

``` bash
[samuel tools]$ cwltool --conformance-test samtools-view.cwl 
/home/samuel/.pyenv/versions/2.7.11/bin/cwltool 1.0.20160427142240
Traceback (most recent call last):
  File "/home/samuel/.pyenv/versions/2.7.11/bin/cwltool", line 9, in <module>
    load_entry_point('cwltool==1.0.20160427142240', 'console_scripts', 'cwltool')()
  File "/home/samuel/.pyenv/versions/2.7.11/lib/python2.7/site-packages/cwltool/main.py", line 590, in main
    stdout=stdout)
  File "/home/samuel/.pyenv/versions/2.7.11/lib/python2.7/site-packages/cwltool/main.py", line 429, in load_job_order
    toolparser = generate_parser(argparse.ArgumentParser(prog=args.workflow), t, namemap)
  File "/home/samuel/.pyenv/versions/2.7.11/lib/python2.7/site-packages/cwltool/main.py", line 283, in generate_parser
    help=ahelp, action=action, type=atype, default=default)
  File "/home/samuel/.pyenv/versions/2.7.11/lib/python2.7/argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'type'
```

**Comment by samuell** [comment]
Yeah, well, removing the trailing slash from `http://schema.org/` on [line 238 in samtools-view](https://github.com/common-workflow-language/workflows/blob/master/tools/samtools-view.cwl#L238) actually solves the problem for samtools view as well.

**Comment by samuell** [comment]
... and so does escaping / putting a backslash, before the last slash, also:

```yaml
$namespaces:
  s: http://schema.org\/  # <-- like so
```

**Comment by samuell** [comment]
The only way to get past this error, without messing up the schema url, seems to be to use the `>` char and a newline:

```yaml
$namespaces:
  s: >
    http://schema.org/
```

So, then this might be an issue with the tool config rather than with cwltool ...

**Comment by mr-c** [comment]
Hello @samuell, thank you for reporting this.

 `cwltool --conformance-test` is meant to be used with a tool definition and a job file, as part of the testing infrastructure. See  https://github.com/common-workflow-language/cwltool/blob/master/cwltool/cwltest.py#L81 https://github.com/common-workflow-language/workflows/blob/master/test/test.sh and https://github.com/common-workflow-language/workflows/blob/master/test/samtools-view-test.yaml

``` shell
(env) mcrusoe@mrcdev:~/workflows$ cwltool --conformance-test tools/samtools-view.cwl  test/samtools-view-job.json 
/home/mcrusoe/workflows/env/bin/cwltool 1.0.20160504183010
('file:///home/mcrusoe/workflows/tools/samtools-view.cwl', 'https://sparql-test.commonwl.org/schema.rdf')
{
    "args": [
        "samtools", 
        "view", 
        "-@", 
        "4", 
        "-b", 
        "-o", 
        "./test-files/SRR1031972.sorted.bam", 
        "/var/lib/cwl/job468835025_test-files/SRR1031972.Aligned.sortedByCoord.out.bam"
    ]
}
```

**Comment by samuell** [comment]
@mr-c Ah, IC!

**Comment by samuell** [comment]
So, maybe just a more sensible error message would help?

**Comment by manu-chroma** [comment]
Looks like ``--conformance-test`` is removed now. Found this related commit: e84b3590f91d05110c10ad77a244e6c6b6b146f9

**Comment by mr-c** [comment]
Thank you for finding this :-)
