### ISSUE TITLE
Caching fails to work properly when using the same dockerised tool in different steps

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/cwltool#740]
https://github.com/common-workflow-language/cwltool/blob/9e3e720ffc18ade0a19fdbb2bea1bed25e9662ae/cwltool/command_line_tool.py#L299-L302

This uses self.requirement and self.hints, which are mutated when a tool is run:

https://github.com/common-workflow-language/cwltool/blob/9e3e720ffc18ade0a19fdbb2bea1bed25e9662ae/cwltool/docker.py#L39-L40

If a workflow uses the same tool multiple times, whether a cache hit occurs for a step will depend on whether the same tool has been run before or not.

### Inputs

<details><summary>test_workflow.cwl</summary>
<p>

    #!/usr/bin/env cwl-runner

    cwlVersion: v1.0
    class: Workflow

    inputs: []
    outputs: []

    steps:
    task1:
        run: test_tool.cwl
        in:
        message:
            default: one
        out: []
    task2:
        run: test_tool.cwl
        in:
        message:
            default: two
        out: []
</p>
</details>

<details><summary>test_tool.cwl</summary>
<p>

    #!/usr/bin/env cwl-runner

    cwlVersion: v1.0
    class: CommandLineTool
    baseCommand: touch
    requirements:
    DockerRequirement:
        dockerPull: alpine
    inputs:
    message:
        type: string
        inputBinding:
        position: 1
    outputs:
    - id: out
        type: File
        outputBinding:
        glob: "*"
</p>
</details>

### Runs

<details><summary>Run 1</summary>
<p>

    $ python -m cwltool --debug --cachedir test_cache test_workflow.cwl
    /Users/th10/checkouts/cwltool/cwltool/__main__.py 1.0.20180324152842
    Resolved 'test_workflow.cwl' to 'file:///Users/th10/checkouts/cwltool/test_workflow.cwl'
    Parsed job order from command line: {
        "id": "test_workflow.cwl"
    }
    [workflow test_workflow.cwl] initialized from file:///Users/th10/checkouts/cwltool/test_workflow.cwl
    [workflow test_workflow.cwl] start
    [workflow test_workflow.cwl] starting step task1
    [job step task1] job input {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task1/message": "one"
    }
    [job step task1] evaluated job input to {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task1/message": "one"
    }
    [step task1] start
    [job task1] keydictstr is {"DockerRequirement":{"class":"DockerRequirement","dockerPull":"alpine"},"cmdline":["docker","run","alpine","touch","one"]} -> 3a88555659d51a9ec2330d04380240f8
    [job task1] Output of job will be cached in /Users/th10/checkouts/cwltool/test_cache/3a88555659d51a9ec2330d04380240f8
    [job task1] initializing from file:///Users/th10/checkouts/cwltool/test_tool.cwl as part of step task1
    [job task1] {
        "message": "one"
    }
    [job task1] path mappings is {}
    [job task1] command line bindings is [
        {
            "position": [
                -1000000,
                0
            ],
            "datum": "touch"
        },
        {
            "position": [
                1,
                "message"
            ],
            "datum": "one"
        }
    ]
    [job task1] /Users/th10/checkouts/cwltool/test_cache/3a88555659d51a9ec2330d04380240f8$ docker \
        run \
        -i \
        --volume=/Users/th10/checkouts/cwltool/test_cache/3a88555659d51a9ec2330d04380240f8:/private/var/spool/cwl:rw \
        --volume=/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp2l4eeu6t:/tmp:rw \
        --workdir=/private/var/spool/cwl \
        --read-only=true \
        --user=16442:1312 \
        --rm \
        --env=TMPDIR=/tmp \
        --env=HOME=/private/var/spool/cwl \
        alpine \
        touch \
        one
    [job task1] completed success
    [job task1] {
        "out": {
            "location": "file:///Users/th10/checkouts/cwltool/test_cache/3a88555659d51a9ec2330d04380240f8/one",
            "basename": "one",
            "nameroot": "one",
            "nameext": "",
            "class": "File",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "size": 0,
            "http://commonwl.org/cwltool#generation": 0
        }
    }
    [step task1] produced output {}
    [step task1] completed success
    [job task1] Removing input staging directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmpdnakizoe
    [job task1] Removing temporary directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp2l4eeu6t
    [workflow test_workflow.cwl] starting step task2
    [job step task2] job input {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task2/message": "two"
    }
    [job step task2] evaluated job input to {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task2/message": "two"
    }
    [step task2] start
    [job task2] keydictstr is {"DockerRequirement":{"class":"DockerRequirement","dockerImageId":"alpine","dockerPull":"alpine"},"cmdline":["docker","run","alpine","touch","two"]} -> 6cfa521e843e7c924b71f93e1156b7d5
    [job task2] Output of job will be cached in /Users/th10/checkouts/cwltool/test_cache/6cfa521e843e7c924b71f93e1156b7d5
    [job task2] initializing from file:///Users/th10/checkouts/cwltool/test_tool.cwl as part of step task2
    [job task2] {
        "message": "two"
    }
    [job task2] path mappings is {}
    [job task2] command line bindings is [
        {
            "position": [
                -1000000,
                0
            ],
            "datum": "touch"
        },
        {
            "position": [
                1,
                "message"
            ],
            "datum": "two"
        }
    ]
    [job task2] /Users/th10/checkouts/cwltool/test_cache/6cfa521e843e7c924b71f93e1156b7d5$ docker \
        run \
        -i \
        --volume=/Users/th10/checkouts/cwltool/test_cache/6cfa521e843e7c924b71f93e1156b7d5:/private/var/spool/cwl:rw \
        --volume=/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp18ovy8e_:/tmp:rw \
        --workdir=/private/var/spool/cwl \
        --read-only=true \
        --user=16442:1312 \
        --rm \
        --env=TMPDIR=/tmp \
        --env=HOME=/private/var/spool/cwl \
        alpine \
        touch \
        two
    [job task2] completed success
    [job task2] {
        "out": {
            "location": "file:///Users/th10/checkouts/cwltool/test_cache/6cfa521e843e7c924b71f93e1156b7d5/two",
            "basename": "two",
            "nameroot": "two",
            "nameext": "",
            "class": "File",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "size": 0,
            "http://commonwl.org/cwltool#generation": 0
        }
    }
    [step task2] produced output {}
    [step task2] completed success
    [workflow test_workflow.cwl] completed success
    [job task2] Removing input staging directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp3hswvlmo
    [job task2] Removing temporary directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp18ovy8e_
    Removing intermediate output directory /Users/th10/checkouts/cwltool/test_cache/mmtlw31b
    {}
    Final process status is success

</p>
</details>

<details><summary>Run 2</summary>
<p>

    $ python -m cwltool --debug --cachedir test_cache test_workflow.cwl
    /Users/th10/checkouts/cwltool/cwltool/__main__.py 1.0.20180324152842
    Resolved 'test_workflow.cwl' to 'file:///Users/th10/checkouts/cwltool/test_workflow.cwl'
    Parsed job order from command line: {
        "id": "test_workflow.cwl"
    }
    [workflow test_workflow.cwl] initialized from file:///Users/th10/checkouts/cwltool/test_workflow.cwl
    [workflow test_workflow.cwl] start
    [workflow test_workflow.cwl] starting step task1
    [job step task1] job input {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task1/message": "one"
    }
    [job step task1] evaluated job input to {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task1/message": "one"
    }
    [step task1] start
    [job task1] keydictstr is {"DockerRequirement":{"class":"DockerRequirement","dockerPull":"alpine"},"cmdline":["docker","run","alpine","touch","one"]} -> 3a88555659d51a9ec2330d04380240f8
    [job task1] Using cached output in /Users/th10/checkouts/cwltool/test_cache/3a88555659d51a9ec2330d04380240f8
    [step task1] produced output {}
    [step task1] completed success
    [workflow test_workflow.cwl] starting step task2
    [job step task2] job input {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task2/message": "two"
    }
    [job step task2] evaluated job input to {
        "file:///Users/th10/checkouts/cwltool/test_workflow.cwl#task2/message": "two"
    }
    [step task2] start
    [job task2] keydictstr is {"DockerRequirement":{"class":"DockerRequirement","dockerPull":"alpine"},"cmdline":["docker","run","alpine","touch","two"]} -> 5115cb5a928586f413deadf8090375a9
    [job task2] Output of job will be cached in /Users/th10/checkouts/cwltool/test_cache/5115cb5a928586f413deadf8090375a9
    [job task2] initializing from file:///Users/th10/checkouts/cwltool/test_tool.cwl as part of step task2
    [job task2] {
        "message": "two"
    }
    [job task2] path mappings is {}
    [job task2] command line bindings is [
        {
            "position": [
                -1000000,
                0
            ],
            "datum": "touch"
        },
        {
            "position": [
                1,
                "message"
            ],
            "datum": "two"
        }
    ]
    [job task2] /Users/th10/checkouts/cwltool/test_cache/5115cb5a928586f413deadf8090375a9$ docker \
        run \
        -i \
        --volume=/Users/th10/checkouts/cwltool/test_cache/5115cb5a928586f413deadf8090375a9:/private/var/spool/cwl:rw \
        --volume=/private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmph12do9a5:/tmp:rw \
        --workdir=/private/var/spool/cwl \
        --read-only=true \
        --user=16442:1312 \
        --rm \
        --env=TMPDIR=/tmp \
        --env=HOME=/private/var/spool/cwl \
        alpine \
        touch \
        two
    [job task2] completed success
    [job task2] {
        "out": {
            "location": "file:///Users/th10/checkouts/cwltool/test_cache/5115cb5a928586f413deadf8090375a9/two",
            "basename": "two",
            "nameroot": "two",
            "nameext": "",
            "class": "File",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "size": 0,
            "http://commonwl.org/cwltool#generation": 0
        }
    }
    [step task2] produced output {}
    [step task2] completed success
    [workflow test_workflow.cwl] completed success
    [job task2] Removing input staging directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmpkma3bhie
    [job task2] Removing temporary directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmph12do9a5
    Removing intermediate output directory /Users/th10/checkouts/cwltool/test_cache/025t0_5x
    {}
    Final process status is success
</p>
</details>

---

From the above output, you can see that task2 doesn't have a cache hit, as task1 didn't run, due to it being cached.

A simple way to fix this is to add a `original_requirements` and `original_hints` property, which doesn't get mutated by cwltool - this can be used for cache decisions. I can have a look at submitting a PR for this.

## Your Environment
* cwltool version: 1.0.20180324152842

**Comment by mr-c** [comment]
Ah, the re-used Process has its `DockerRequirement` adjusted to include the `dockerImageId` and thus the caching fails:
`{"DockerRequirement":{"class":"DockerRequirement","dockerImageId":"alpine","dockerPull":"alpine"},`
