### ISSUE TITLE
File entries of listing in a directory input do not have size filled in

### ISSUE THREAD

**Issue by pkp124** [common-workflow-language/cwltool#749]
Hello,

The file entries in the listing field of a directory input only fills in the location and basename fields.
Please see https://github.com/common-workflow-language/cwltool/blob/33c2358a76c57ae06888203a2384c869b87e369e/cwltool/pathmapper.py#L132

Filling in the other fields of the file structure may be helpful. For now, I have the use case of using the "size" field for resource calculations. 

Thanks

**Comment by mr-c** [comment]
Hello @pkp124 , I can confirm that this is a bug in `cwltool`.

**Comment by mr-c** [comment]
Here's a conformance test that confirms the bug: https://github.com/common-workflow-language/common-workflow-language/pull/690

**Comment by mr-c** [comment]
And here's a fix that passes the above conformance test https://github.com/common-workflow-language/cwltool/pull/750

**Comment by pkp124** [comment]
Thanks @mr-c
