### ISSUE TITLE
singularity --contain incompatibility with beegfs 

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#753]
It looks like the `--contain`, `--pid` and `--ipc` flags cause more troubles and helping:
https://github.com/common-workflow-language/cwltool/blob/master/cwltool/singularity.py#L216

if I remove these it works. not sure if beegfs is the problem.

**Comment by gijzelaerr** [comment]
```
$ mkdir -p testcache testtemp
$ singularity exec --contain --ipc --pid --bind `pwd`/testcache:/var/spool/cwl:rw --bind `pwd`/testtemp:/tmp:rw --pwd /var/spool/cwl `pwd`/gijzelaerr-spiel.img bash 
gijs@master001:~$ exit   # note the path, it is not /var/spool/cwl
gijs@master001:~/spiel$ singularity exec --pid --bind `pwd`/testcache:/var/spool/cwl:rw --bind `pwd`/testtemp:/tmp:rw --pwd /var/spool/cwl `pwd`/gijzelaerr-spiel.img bash 
gijs@master001:/var/spool/cwl$ exit   # but now it is
```

**Comment by mr-c** [comment]
What Linux distribution and kernel version?

**Comment by gijzelaerr** [comment]
it does works properly on:

Ubuntu 18.04
singularity 2.5.1-dist
Linux 4.15.0-20-generic
fs ext4

```
λ  singularity exec --contain --ipc --pid --bind `pwd`/testcache:/var/spool/cwl:rw --bind `pwd`/testtemp:/tmp:rw --pwd /var/spool/cwl `pwd`/gijzelaerr-spiel.img bash
gijs@tshikovski:/var/spool/cwl$ ^C
```

**Comment by mr-c** [comment]
Huh, that's a big difference in kernels, OS, and Singularity version..

**Comment by gijzelaerr** [comment]
Just removing the `--contain` flag seems to be enough. I've examined the config file, but don't see anything weird. check yourself if you want :) https://gist.github.com/gijzelaerr/7571b1474b2da95affc3168a39f396ca

**Comment by mr-c** [comment]
Looking back, it seems that Singularity 2.5.x doesn't have the issue

Given that http://singularity.lbl.gov/release-2-5-0 says
> **Singularity 2.5 should be installed immediately and all previous versions of Singularity should be removed.** Many of the vulnerabilities fixed in this release are expected to affect all Linux distributions regardless of whether they implement overlayfs. There are no mitigations or workarounds for these issues outside of updating Singularity.

Can you confirm that Singularity 2.5.0 or 2.5.1 on beegfs works with `--contain`?

**Comment by mr-c** [comment]
Closing for now. Please re-open if this is still a problem
