### ISSUE TITLE
mypy bug reference

### ISSUE THREAD

**Issue by kghosesbg** [common-workflow-language/cwltool#784]
https://github.com/common-workflow-language/cwltool/blob/65203c767d89d9ec779848a2ee80ab0a3c21de06/cwltool/workflow.py#L319

Hi @tetron , @gijzelaerr,

I was going over the cwltool code (nice code, BTW. A joy to read and explore!) and I was exploring scatter and I found this reference to a mypy bug. This mypy bug is now closed. Was the current code a workaround? Can this workaround be dropped? (forgive me, I'm unfamiliar with mypy)

Thanks!
-Kaushik

**Comment by mr-c** [comment]
Hey @kghosesbg , good catch. You are correct, and I've already done so over in https://github.com/common-workflow-language/cwltool/pull/747

**Comment by mr-c** [comment]
#747 is merged so I'm closing this :-)
