### ISSUE TITLE
--memory being set when neither ramMin and ramMax are set

### ISSUE THREAD

**Issue by Karhide** [common-workflow-language/cwltool#830]
If I roll back to the previous version, the default --memory flag is not used, but on 1.0.20180711112827 we are seeing '--memory=1024' applied by default.

Note this was experienced running containerised tools. Have not tested similar effects in locally installed tools.

Thanks.

**Comment by mr-c** [comment]
Hello @Karhide , thank you for your issue.

This is new behaviour, and while it is useful for testing `ramMin` and `ramMax` for better portability of CWL workflows and tools, it gives a bad experience for more casual use.

Therefore I propose that we hide this behaviour behind a flag like `--strict-memory-limit`

**Comment by Karhide** [comment]
that sounds good!

**Comment by dleehr** [comment]
I mentioned a possible related bug this morning, but as noted in the referenced issue, I missed something in our calculations and was overcommitting resources. 

I will probably use the `--strict-memory-limit` option to smoke out these things, but agree that it shouldn't be the default

**Comment by mr-c** [comment]
A PR to fix this is at https://github.com/common-workflow-language/cwltool/pull/835 -- feedback and reviews are welcome.

**Comment by andrewyatz** [comment]
I'm not really a python or cwl expert so my comments would be pretty superficial. Happy to give them if you want though

**Comment by mr-c** [comment]
This has been released in `cwltool` [v1.0.20180721142728](https://pypi.org/project/cwltool/1.0.20180721142728/)
