### ISSUE TITLE
inputs array of secondaryFiles not processed

### ISSUE THREAD

**Issue by jeremiahsavage** [common-workflow-language/cwltool#88]
I am attempting to associate a `secondaryFile` (BAI) with each `File` is an `array` (of BAMs).
I get desired behavior with the Jan26 release [0], but the following Jan27 release [1] breaks our cwl.

This the the cwl snippet

```
cwlVersion: "cwl:draft-2"
requirements:
  - import: node-engine.cwl
  - import: envvar-global.cwl
  - class: DockerRequirement
    dockerPull: quay.io/___
class: CommandLineTool
inputs:
  - id: "#input_bam_path"
    type:
      type: array
      items: File
      inputBinding:
        prefix: --bam_path
        secondaryFiles:
          - engine: node-engine.cwl
            script: |
              {
              return {"path": $self.path.slice(0,-4)+".bai", "class": "File"};
              }
```

with `--debug` gives the desired bindings with the Jan26 release [2], but not with the Jan27 release [3].

I ran a `diff` [4] of the two releases. It looks like `secondaryFiles` are now in `schema` instead of `binding`. Is the post-Jan27 behavior the desired to our cwl?
## 

[0]
https://pypi.python.org/packages/da/93/fd0885312894cda09ad4bcb04c7091ec7b6da15ab10e14f468cdc54caed5/cwltool-1.0.20160126211726.tar.gz

[1]
https://pypi.python.org/packages/8e/b3/c9326f44854d8ca71668070fb09746f4b0c1fe4f5d749de7db3d737eee88/cwltool-1.0.20160127144612.tar.gz

[2]

```
    {
        "secondaryFiles": [
            "${\nreturn {\"path\": self.path.slice(0,-4)+\".bai\", \"class\": \"File\"};\n}\n"
        ], 
        "prefix": "--bam_path", 
        "do_eval": {
            "path": "/tmp/job633706396_ubuntu/SCRATCH/47b42e81-2500-4ebc-a0c2-acd3187cc2f0_513/test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bam", 
            "class": "File", 
            "secondaryFiles": [
                {
                    "path": "/tmp/job633706396_ubuntu/SCRATCH/47b42e81-2500-4ebc-a0c2-acd3187cc2f0_513/test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bai", 
                    "class": "File"
                }
            ]
        }, 
        "valueFrom": {
            "path": "/tmp/job633706396_ubuntu/SCRATCH/47b42e81-2500-4ebc-a0c2-acd3187cc2f0_513/test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bam", 
            "class": "File", 
            "secondaryFiles": [
                {
                    "path": "/tmp/job633706396_ubuntu/SCRATCH/47b42e81-2500-4ebc-a0c2-acd3187cc2f0_513/test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bai", 
                    "class": "File"
                }
            ]
        }, 
        "position": [
            0, 
            0, 
            "input_bam_path", 
            "input_bam_path"
        ]
    }, 
```

[3]

```
    {
        "position": [
            0, 
            0, 
            "input_bam_path", 
            "input_bam_path"
        ], 
        "prefix": "--bam_path", 
        "do_eval": {
            "path": "/tmp/job557517512_test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bam", 
            "class": "File"
        }, 
        "valueFrom": {
            "path": "/tmp/job557517512_test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bam", 
            "class": "File"
        }
    }, 
```

[4]
https://gist.github.com/jeremiahsavage/c82b38027be30eccbf9b47361c8f7fbb

**Comment by tetron** [comment]
What happens if you try to run it with the latest cwltool?

You are correct that secondaryFiles moved up one level between draft-2 and draft-3.  However, if you are writing draft-2 documents you should be using the draft-2 syntax.  Recent versions of cwltool (since 3 weeks ago or so) have tightened up validation for specific spec version.  Prior to that cwltool incorrectly accepted invalid documents that blended draft-2 and draft-3 syntax, it is possible that is where you are getting into trouble.  Does that help?

**Comment by jeremiahsavage** [comment]
With latest `cwltool 1.0.20160523144113` the secondaryFile is not picked up.

```
    {
        "position": [
            0, 
            0, 
            "input_bam_path", 
            "input_bam_path"
        ], 
        "prefix": "--bam_path", 
        "do_eval": {
            "path": "/var/lib/cwl/job805995621_ubuntu/SCRATCH/47b42e81-2500-4ebc-a0c2-acd3187cc2f0_513/test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bam", 
            "containerfs": true, 
            "class": "File"
        }, 
        "valueFrom": {
            "path": "/var/lib/cwl/job805995621_ubuntu/SCRATCH/47b42e81-2500-4ebc-a0c2-acd3187cc2f0_513/test/C440.TCGA-IN-8462-01A-11D-2340-08.1.bam", 
            "containerfs": true, 
            "class": "File"
        }
    }, 
```

I'll try altering the syntax.

**Comment by jeremiahsavage** [comment]
I've created a self-contained test (just used `echo`) in `cwl:draft-3` which also doesn't associate secondaryFiles. This is the debug output:
```
$ cwltool --strict --debug ~/code/cocleaning-cwl/tools/array_secondary_3.cwl.yaml --bam_path test.bam --bam_path test.bam --bam_path test.bam
/home/jeremiah/.virtualenvs/p2/bin/cwltool 1.0.20160523144113
Parsed job order from command line: {
    "bam_path": [
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }
    ], 
    "id": "/home/jeremiah/code/cocleaning-cwl/tools/array_secondary_3.cwl.yaml", 
    "job_order": null
}
[job array_secondary_3.cwl.yaml] initializing from file:///home/jeremiah/code/cocleaning-cwl/tools/array_secondary_3.cwl.yaml
[job array_secondary_3.cwl.yaml] {
    "bam_path": [
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }
    ], 
    "job_order": null
}
[job array_secondary_3.cwl.yaml] path mappings is {
    "test.bam": [
        "/home/jeremiah/Downloads/test.bam", 
        "/home/jeremiah/Downloads/test.bam"
    ]
}
[job array_secondary_3.cwl.yaml] command line bindings is [
    {
        "shellQuote": false, 
        "position": [
            1, 
            0
        ], 
        "valueFrom": null, 
        "do_eval": "${ var bam_list = \"\"; for (var i = 0; i < inputs.bam_path.length; i ++) { bam_list += \" echo \" + inputs.bam_path[i].path.split('/').slice(-1)[0] + \" >> bam.list &&\" } return bam_list.slice(0,-2) }"
    }
]
[job array_secondary_3.cwl.yaml] /home/jeremiah/Downloads$ /bin/sh \
    -c \
     echo test.bam >> bam.list && echo test.bam >> bam.list && echo test.bam >> bam.list 
[job array_secondary_3.cwl.yaml] completed success
[job array_secondary_3.cwl.yaml] {
    "bam_list": {
        "size": 81, 
        "path": "/home/jeremiah/Downloads/bam.list", 
        "checksum": "sha1$b4231c7a667fc5149b8e9856688fc3713817ad32", 
        "class": "File"
    }
}
Final process status is success
[job array_secondary_3.cwl.yaml] Removing temporary directory /tmp/tmpE5ZoVg
{
    "bam_list": {
        "size": 81, 
        "path": "/home/jeremiah/Downloads/bam.list", 
        "checksum": "sha1$b4231c7a667fc5149b8e9856688fc3713817ad32", 
        "class": "File"
    }
}
```
and this the cwl
```
#!/usr/bin/env cwl-runner

cwlVersion: "cwl:draft-3"

requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement

class: CommandLineTool

inputs:
  - id: bam_path
    type:
      type: array
      items: File
    secondaryFiles: |
      ${
      return {"path": $self.path.slice(0,-4)+".bai", "class": "File"};
      }

outputs:
  - id: bam_list
    type: File
    outputBinding:
      glob: "bam.list"
  # - id: bai_list
  #   type: File
  #   outputBinding:
  #     glob: "bai.list"

arguments:
  - valueFrom: ${
        var bam_list = "";
        for (var i = 0; i < inputs.bam_path.length; i ++) {
          bam_list += " echo " + inputs.bam_path[i].path.split('/').slice(-1)[0] + " >> bam.list &&"
        }
        return bam_list.slice(0,-2)
        }
    position: 1
    shellQuote: false

baseCommand: []
```

**Comment by Shenglai** [comment]
With latest cwltool 1.0.20160523144113 the secondaryFile is not picked up even with `cwlVersion: "cwl:draft-2"`

**Comment by jeremiahsavage** [comment]
Fixed with https://github.com/common-workflow-language/cwltool/pull/91

**Comment by jeremiahsavage** [comment]
Actually, the fix only works if cwl is draft-2, and causes crash if draft-3. So don't merge.

**Comment by jeremiahsavage** [comment]
Now tested successfully with draft-3 using the below cwl and output (also tested with a gatk indelrealigner tool that requires bai for each bam).

 
cwl:
```
#!/usr/bin/env cwl-runner

cwlVersion: "cwl:draft-3"

requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement

class: CommandLineTool

inputs:
  - id: bam_path
    type:
      type: array
      items: File
      secondaryFiles: |
        ${
        return {"path": self.path.slice(0,-4)+".bai", "class": "File"};
        }

outputs:
  - id: bam_list
    type: File
    outputBinding:
      glob: "bam.list"

arguments:
  - valueFrom: ${
        var bam_list = "";
        for (var i = 0; i < inputs.bam_path.length; i ++) {
          bam_list += " echo " + inputs.bam_path[i].path.split('/').slice(-1)[0] + " >> bam.list &&"
        }
        return bam_list.slice(0,-2)
        }
    position: 1
    shellQuote: false

baseCommand: []
```

output
```
(p2_fix)[jeremiah@localhost Downloads]$ cwltool --strict --debug ~/code/cocleaning-cwl/tools/array_secondary_3.cwl.yaml --bam_path test.bam --bam_path test.bam --bam_path test.bam
/home/jeremiah/.virtualenvs/p2_fix/bin/cwltool 1.0.20160531173804
Parsed job order from command line: {
    "bam_path": [
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }
    ], 
    "id": "/home/jeremiah/code/cocleaning-cwl/tools/array_secondary_3.cwl.yaml", 
    "job_order": null
}
[job array_secondary_3.cwl.yaml] initializing from file:///home/jeremiah/code/cocleaning-cwl/tools/array_secondary_3.cwl.yaml
[job array_secondary_3.cwl.yaml] {
    "bam_path": [
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }, 
        {
            "path": "test.bam", 
            "class": "File"
        }
    ], 
    "job_order": null
}
[job array_secondary_3.cwl.yaml] path mappings is {
    "test.bam": [
        "/home/jeremiah/Downloads/test.bam", 
        "/home/jeremiah/Downloads/test.bam"
    ], 
    "test.bai": [
        "/home/jeremiah/Downloads/test.bai", 
        "/home/jeremiah/Downloads/test.bai"
    ]
}
[job array_secondary_3.cwl.yaml] command line bindings is [
    {
        "shellQuote": false, 
        "position": [
            1, 
            0
        ], 
        "valueFrom": null, 
        "do_eval": "${ var bam_list = \"\"; for (var i = 0; i < inputs.bam_path.length; i ++) { bam_list += \" echo \" + inputs.bam_path[i].path.split('/').slice(-1)[0] + \" >> bam.list &&\" } return bam_list.slice(0,-2) }"
    }
]
[job array_secondary_3.cwl.yaml] /home/jeremiah/Downloads$ /bin/sh \
    -c \
     echo test.bam >> bam.list && echo test.bam >> bam.list && echo test.bam >> bam.list 
[job array_secondary_3.cwl.yaml] completed success
[job array_secondary_3.cwl.yaml] {
    "bam_list": {
        "size": 54, 
        "path": "/home/jeremiah/Downloads/bam.list", 
        "checksum": "sha1$05dd8404a864139f7f5afd0cd560044c28a8f41e", 
        "class": "File"
    }
}
Final process status is success
[job array_secondary_3.cwl.yaml] Removing temporary directory /tmp/tmp4bF0hg
{
    "bam_list": {
        "size": 54, 
        "path": "/home/jeremiah/Downloads/bam.list", 
        "checksum": "sha1$05dd8404a864139f7f5afd0cd560044c28a8f41e", 
        "class": "File"
    }
}
(p2_fix)[jeremiah@localhost Downloads]$ 
```

**Comment by mr-c** [comment]
Hello @jeremiahsavage, thank you for your issue and PR.

I'm trying to understand your use case better: As @chapmanb points out in https://groups.google.com/d/msg/common-workflow-language/u9q03lFBHpQ/L9on3M1MAgAJ it would seem that the `secondaryFiles` with a string value of `.bai` or `^.bai` should meet your needs.

**Comment by jeremiahsavage** [comment]
Hi @mr-c . Yes. I've tried using the `.bai` and `^.bai` methods suggested.  But using latest (post January 26) version of `cwltool`, secondaryFiles were not attached to items of an array. For Jan26, and before the bug does not exist. Perhaps @chapmanb is using a branch prior to Jan26?

I used a lot of `print()` statements to see that `secondaryFiles` was not being passed to each item of the array at the point the patch touches.

The fix allows cwl written in `draft-2` or `draft-3` to pass secondaryFiles through arrays.

For example.
cwl:draft-2 case:
    cwl: https://gist.github.com/jeremiahsavage/f49146e32e098697494d74b20ea10526
    latest cwltool debug output (no bai): https://gist.github.com/jeremiahsavage/72172b5eeca50a654ee1732bd131317e
    with patch debug output (gets bai): https://gist.github.com/jeremiahsavage/a8b923d9e50ed6ba34875f7ccae4d206

cwl:draft-3 case:
   cwl (`^.bai`): https://gist.github.com/jeremiahsavage/760ffdae6a5220d327b997269b5f52ee
   latest cwltool debug output (no bai): https://gist.github.com/jeremiahsavage/760ffdae6a5220d327b997269b5f52ee
   with patch debug output (gets bai):  https://gist.github.com/jeremiahsavage/f9b3e989d5d185015e1d7317e14591e1

**Comment by chapmanb** [comment]
Jeremiah;
I'm using 1.0.20160427142240 from bioconda (https://bioconda.github.io/). I'm not sure about the very latest version, Peter would be most helpful on assessing that. It would be useful to know if you still run into issues with the version in bioconda. You can install with:
```
/path/to/anaconda/bin/conda -c bioconda cwltool
```
Sorry to not have a good idea why you're seeing this but hopefully this helps some.

**Comment by jeremiahsavage** [comment]
Hi Brad and Michael,

I've created a true minimal test case to show the issue and the fix. In this test, the process will actually fail instead of just showing the pickup of the secondaryFile in the `--debug` output I was reporting before.

Three step instructions at:
https://github.com/jeremiahsavage/array_secondary

Docker has to be involved, as when docker is not use, paths are not redirected (to something like `/var/lib/cwl/job445880475`), so the issue of secondaryFiles not passing, is masked.

I've tested with the latest bioconda (to show issue) and with the fix (in a python virtualenv). The output is in the `README.md`

**Comment by mr-c** [comment]
Thank you Jeremiah for your detailed debugging. We are a bit swamped with
getting some other changes done in time for 1.0 of the standard. My work
day is over; but I will take a look tomorrow.
Pe 7 iun. 2016 8:09 p.m., "Jeremiah H. Savage" <notifications@github.com> a
scris:

**Comment by jeremiahsavage** [comment]
Just a ping. It would be great if this was fixed in 1.0
test: https://github.com/jeremiahsavage/array_secondary
fix: https://github.com/common-workflow-language/cwltool/pull/91

**Comment by mr-c** [comment]
Fix is now in https://github.com/common-workflow-language/cwltool/pull/170 (but needs some assistance)

**Comment by kmhernan** [comment]
@mr-c I am having this issue with v1.0 and cwltool 1.0.20160913171024 

For example:

```
  known_vcf:
    type:
      type: array
      items: File
      inputBinding:
        prefix: --known
    doc: "Input VCF file(s) with known indels."
    default: null
    secondaryFiles:
      - ".tbi"
    inputBinding:
      position: 3
```

Will not bind the secondaryFiles and no information about them is available in the `--debug` output.

**Comment by kmhernan** [comment]
@mr-c Looking through this, it seems like it is both a critical problem (i.e., basically we are unable to use arrays of files that have secondary files! I am unable to run 90% of my pipelines because of this) and a difficult one to fix. When I was playing with the cwltool I didn't see any information about the secondaryFiles passed to the `schema` or `datum` variables in the `bind_input()` member function of the `Builder` class. Any suggestions?

**Comment by tetron** [comment]
Can someone check if this was fixed with #211 ?

**Comment by jeremiahsavage** [comment]
Yes. This is fixed for tools which are written in Draft-3. In v1.0, it does not work, as v1.0 does not have `secondaryFiles` as a valid field in `CommandInputRecordSchema`. I currently include draft-3 tools in v1.0 workflows. It would be nice if this were brought back at some point.

**Comment by tetron** [comment]
> Yes. This is fixed for tools which are written in Draft-3. In v1.0, it does not work, as v1.0 does not have secondaryFiles as a valid field in CommandInputRecordSchema. I currently include draft-3 tools in v1.0 workflows. It would be nice if this were brought back at some point.

That sounds like a mistake that was introduced when the spec was being refactored between draft-3 and v1.0.  Can you file an issue on the spec repository so we can fix it in the next release?
