### ISSUE TITLE
InitialWorkDirRequirement with Expression in listing

### ISSUE THREAD

**Issue by wgerlach** [common-workflow-language/cwltool#881]
## Expected Behavior
cwltool should parse an array of Expressions in the lisiting field of InitialWorkDirRequirement as specified in
[https://www.commonwl.org/v1.0/CommandLineTool.html#InitialWorkDirRequirement](https://www.commonwl.org/v1.0/CommandLineTool.html#InitialWorkDirRequirement)

## Actual Behavior
I get: `WorkflowException: 'list' object has no attribute 'get'`

It seems the cwltool does not expect an array in the listing field.

## Workflow Code
working compliance test v1.0/dir5.cwl
```
class: CommandLineTool
cwlVersion: v1.0
requirements:
  - class: ShellCommandRequirement
  - class: InitialWorkDirRequirement
    listing: $(inputs.indir.listing)
inputs:
  indir: Directory
outputs:
  outlist:
    type: File
    outputBinding:
      glob: output.txt
arguments: ["find", "-L", ".", "!", "-path", "*.txt",
  {shellQuote: false, valueFrom: "|"},
  "sort"]
stdout: output.txt
```
vs

modified compliance test v1.0/dir5.cwl , listing is now an array:
```
class: CommandLineTool
cwlVersion: v1.0
requirements:
  - class: ShellCommandRequirement
  - class: InitialWorkDirRequirement
    listing: 
      - $(inputs.indir.listing)
inputs:
  indir: Directory
outputs:
  outlist:
    type: File
    outputBinding:
      glob: output.txt
arguments: ["find", "-L", ".", "!", "-path", "*.txt",
  {shellQuote: false, valueFrom: "|"},
  "sort"]
stdout: output.txt
```

## Full Traceback
```pytb
Got workflow error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cwltool/executors.py", line 110, in run_jobs
    for job in jobiter:
  File "/usr/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 430, in job
    self.updatePathmap(builder.outdir, builder.pathmapper, l)
  File "/usr/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 258, in updatePathmap
    for sf in fn.get("secondaryFiles", []):
AttributeError: 'list' object has no attribute 'get'
Workflow error:
'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cwltool/main.py", line 588, in main
    logger=_logger)
  File "/usr/lib/python2.7/site-packages/cwltool/executors.py", line 34, in __call__
    return self.execute(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cwltool/executors.py", line 83, in execute
    self.run_jobs(process, job_order_object, logger, runtimeContext)
  File "/usr/lib/python2.7/site-packages/cwltool/executors.py", line 124, in run_jobs
    raise WorkflowException(Text(e))
WorkflowException: 'list' object has no attribute 'get'
```

## Your Environment
* cwltool version: 
1.0.20180622214234

**Comment by wgerlach** [comment]
I see that the Expression returns an array, it would not make sense to have an array of array. Still, then the specification should not allow an array of Expressions. Unless those Expressions can return Files and Directories. This should be clearer in the specification.

**Comment by mr-c** [comment]
Hello @wgerlach , thanks for your issue. This has already been proposed for CWL v1.1 https://github.com/common-workflow-language/common-workflow-language/issues/412 https://github.com/common-workflow-language/cwl-v1.1/pull/3

Yes, the top level CWL expression must validate to `{type: array, items: [File, Directory]}.`, any expression fields inside the array should return either a File object or a Directory object in v1.x. It has been proposed that in CWL v1.1 that expressions within the array can return arrays as well.
