### ISSUE TITLE
Tools unable to write files inside Docker containers

### ISSUE THREAD

**Issue by psafont** [common-workflow-language/cwltool#905]
Under some circumstances the directories used for the volume mounts are not created before running a tool in a Docker container.

This forces the Docker daemon to create those directories, with the unfortunate choice of creating them with the uid and guid of the `root` user. This causes the tool to be unable to write files to the output directory.

I discovered this using the kernel audit, but I doubt it'd be useful to see.

For reference, this is the type of command that cwltool creates when triggering this behaviour:

```
docker \
         run \
         -i \
         --volume=/tmp/non-existant-directory:/var/spool/cwl:rw \
         --volume=/tmp/another-non-existant-folder:/tmp:rw \
         --workdir=/var/spool/cwl \
         --read-only=true \
         --user=1000:1000 \
         --rm \
         --env=TMPDIR=/tmp \
         --env=HOME=/var/spool/cwl \
         ebiwp/ebitools-container \
         ncbiblast_lwp.pl \
         --jobid \
         ncbiblast-R20180905-104903-0467-36809650-p1m \
         --outformat \
         xml \
         --polljob
```
output:
```
Creating result file: ncbiblast-R20180905-104903-0467-36809650-p1m.xml.xml
Error: unable to open output file ncbiblast-R20180905-104903-0467-36809650-p1m.xml.xml (Permission denied) at /usr/src/ebitools/ncbiblast_lwp.pl line 1214.
```

**Comment by FarahZKhan** [comment]
@psafont I remember seeing the same issue in case of SAMtools execution. 
The work around that we used at that time was 
```
cwltool --no-match-user cwlfile.cwl jobfile.json
```
Not sure if this is the only solution but you can try running with this if it helps.

**Comment by psafont** [comment]
Thanks for the workaround!

I'll still try to hunt down the reason why the drectory is not created in cwltool

**Comment by psafont** [comment]
The workaround just allows tools to be run as root inside Docker, it doesn't change that the temporary folders are created by `dockerd`.

**Comment by FarahZKhan** [comment]
Ah okay, I think this is a different issue then. We got a similar Error message so I thought this might solve the issue.

**Comment by psafont** [comment]
I should have said that your suggestion works for my use-case, but I don't like all the tools being run as root.

**Comment by mr-c** [comment]
@psafont What is your Python version, kernel, local filesystem type, and Linux distribution?

**Comment by psafont** [comment]
Nevermind, it was a problem on how I configured the service, it had a private /tmp folder, which was triggering the docker daemon to create the folders on its own, leading to this behaviour.
