### ISSUE TITLE
cwltool pulls in docker images for all tasks when singularity is enabled

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#932]
When I run a pipeline with multiple tasks and the same DockerPull defined in each task singularity will downlaod and store the image layers for every task. This causes unnecessary disk usage and explodes with big pipelines.

**Comment by mr-c** [comment]
I think this has been fixed. Also https://github.com/common-workflow-language/cwl-utils#pull-the-all-referenced-software-container-images can be used to cache the images ahead of time.
